Repository LinuxForHealth/FHIR, pull requests merged in 2019-10, with the labels that each got.

#185 CI: Tests report failure when messages are sent back. #184
  fhir-server-test/pom.xml
  fhir-server-test/src/test/java/com/ibm/fhir/server/test/FHIRNotificationServiceClientEndpoint.java
  fhir-server-test/src/test/java/com/ibm/fhir/server/test/FHIRServerTestBase.java
  fhir-server-test/src/test/java/com/ibm/fhir/server/test/WebSocketNotificationsTest.java
Labels: automation, bug

#156 Fix for ear creation #57
  fhir-parent/pom.xml
Labels: bug

#149 Issue 115 - Support return preference
  .github/workflows/build.yml
  README.md
  fhir-bulkimportexport-webapp/src/main/java/com/ibm/fhir/bulkexport/BulkExportBatchLet.java
  fhir-bulkimportexport-webapp/src/main/java/com/ibm/fhir/bulkexport/ChunkReader.java
  fhir-client/src/main/java/com/ibm/fhir/client/FHIRClient.java
  fhir-client/src/main/java/com/ibm/fhir/client/impl/FHIRClientImpl.java
  fhir-config/src/main/java/com/ibm/fhir/config/FHIRRequestContext.java
  fhir-core/src/main/java/com/ibm/fhir/core/HTTPReturnPreference.java
  fhir-model/src/main/java/com/ibm/fhir/model/util/FHIRUtil.java
  fhir-operation/src/main/java/com/ibm/fhir/rest/FHIRRestOperationResponse.java
  fhir-persistence-jdbc/pom.xml
  fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/impl/FHIRPersistenceJDBCImpl.java
  fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/impl/FHIRPersistenceJDBCNormalizedImpl.java
  fhir-persistence-jdbc/src/test/java/com/ibm/fhir/persistence/jdbc/test/spec/CreateOperation.java
  fhir-persistence-jdbc/src/test/java/com/ibm/fhir/persistence/jdbc/test/spec/DeleteOperation.java
  fhir-persistence-jdbc/src/test/java/com/ibm/fhir/persistence/jdbc/test/spec/HistoryOperation.java
  fhir-persistence-jdbc/src/test/java/com/ibm/fhir/persistence/jdbc/test/spec/ReadOperation.java
  fhir-persistence-jdbc/src/test/java/com/ibm/fhir/persistence/jdbc/test/spec/UpdateOperation.java
  fhir-persistence-jdbc/src/test/java/com/ibm/fhir/persistence/jdbc/test/spec/VReadOperation.java
  fhir-persistence-jdbc/src/test/java/testng.xml
  fhir-persistence/src/main/java/com/ibm/fhir/persistence/FHIRPersistence.java
  fhir-persistence/src/main/java/com/ibm/fhir/persistence/FHIRPersistenceFactory.java
  fhir-persistence/src/main/java/com/ibm/fhir/persistence/FHIRPersistenceTransaction.java
  fhir-persistence/src/main/java/com/ibm/fhir/persistence/MultiResourceResult.java
  fhir-persistence/src/main/java/com/ibm/fhir/persistence/PropertyBasedFHIRPersistenceFactory.java
  fhir-persistence/src/main/java/com/ibm/fhir/persistence/SingleResourceResult.java
  fhir-persistence/src/test/java/com/ibm/fhir/persistence/search/test/AbstractPLSearchTest.java
  fhir-persistence/src/test/java/com/ibm/fhir/persistence/test/MockPersistenceImpl.java
  fhir-persistence/src/test/java/com/ibm/fhir/persistence/test/common/AbstractDeleteTest.java
  fhir-persistence/src/test/java/com/ibm/fhir/persistence/test/common/AbstractPersistenceTest.java
  fhir-persistence/src/test/java/com/ibm/fhir/persistence/test/common/AbstractQueryAuditEventTest.java
  fhir-persistence/src/test/java/com/ibm/fhir/persistence/test/common/AbstractQueryChainedParmTest.java
  fhir-persistence/src/test/java/com/ibm/fhir/persistence/test/common/AbstractQueryContractTest.java
  fhir-persistence/src/test/java/com/ibm/fhir/persistence/test/common/AbstractQueryDeviceTest.java
  fhir-persistence/src/test/java/com/ibm/fhir/persistence/test/common/AbstractQueryEncounterTest.java
  fhir-persistence/src/test/java/com/ibm/fhir/persistence/test/common/AbstractQueryGroupTest.java
  fhir-persistence/src/test/java/com/ibm/fhir/persistence/test/common/AbstractQueryLocationTest.java
  fhir-persistence/src/test/java/com/ibm/fhir/persistence/test/common/AbstractQueryMedicationTest.java
  fhir-persistence/src/test/java/com/ibm/fhir/persistence/test/common/AbstractQueryMultiResourceTest.java
  fhir-persistence/src/test/java/com/ibm/fhir/persistence/test/common/AbstractQueryPatientTest.java
  fhir-persistence/src/test/java/com/ibm/fhir/persistence/test/common/AbstractQueryPractitionerTest.java
  fhir-persistence/src/test/java/com/ibm/fhir/persistence/test/common/AbstractQueryQuestionnaireRespTest.java
  fhir-persistence/src/test/java/com/ibm/fhir/persistence/test/common/AbstractQueryQuestionnaireTest.java
  fhir-persistence/src/test/java/com/ibm/fhir/persistence/test/common/AbstractQueryRiskAssmtTest.java
  fhir-persistence/src/test/java/com/ibm/fhir/persistence/test/common/AbstractQuerySortTest.java
  fhir-persistence/src/test/java/com/ibm/fhir/persistence/test/common/AbstractSearchAllTest.java
  fhir-server-test/src/test/java/com/ibm/fhir/client/test/FHIRClientTest.java
  fhir-server-test/src/test/java/com/ibm/fhir/server/test/BundleTest.java
  fhir-server-test/src/test/java/com/ibm/fhir/server/test/DeleteTest.java
  fhir-server-test/src/test/java/com/ibm/fhir/server/test/ServerSpecTest.java
  fhir-server-test/src/test/java/com/ibm/fhir/server/test/UpdateTest.java
  fhir-server-test/src/test/java/com/ibm/fhir/server/test/WebSocketNotificationsTest.java
  fhir-server-test/src/test/java/testng.xml
  fhir-server-test/src/test/resources/test.properties
  fhir-server-webapp/pom.xml
  fhir-server/src/main/java/com/ibm/fhir/server/filter/rest/FHIRRestServletFilter.java
  fhir-server/src/main/java/com/ibm/fhir/server/resources/FHIRResource.java
Labels: enhancement

#205 add additional check for Code subtypes in the new types.code subpackage #202
  fhir-search/src/main/java/com/ibm/fhir/search/valuetypes/impl/ValueTypesR4Impl.java
  fhir-server/liberty-config/server.xml
Labels: bug

#211 WebSocket IT Fails intermittently #210
  fhir-parent/pom.xml
  fhir-server-test/src/test/java/com/ibm/fhir/server/test/FHIRNotificationServiceClientEndpoint.java
  fhir-server-test/src/test/java/com/ibm/fhir/server/test/FHIRServerTestBase.java
  fhir-server-test/src/test/java/com/ibm/fhir/server/test/WebSocketNotificationsTest.java
Labels: automation, bug

#207 Manage M2E Settings for fhir-parent #206
  fhir-examples-generator/pom.xml
  fhir-parent/pom.xml
Labels: bug

#209 Replace xmp tag to create valid javadoc #208
  fhir-client/src/main/java/com/ibm/fhir/client/FHIRRequestHeader.java
  fhir-config/src/main/java/com/ibm/fhir/config/PropertyGroup.java
Labels: automation, bug, documentation

#213 Issue 212
  docs/FHIRServerUsersGuide.md
  fhir-client-sample/src/main/resources/fhirkeys.jceks
  fhir-client/src/main/java/com/ibm/fhir/client/FHIRClient.java
  fhir-client/src/main/java/com/ibm/fhir/client/impl/FHIRClientImpl.java
  fhir-client/src/main/java/com/ibm/fhir/client/impl/FHIREncryptionClientFilter.java
  fhir-client/src/test/resources/fhirkeys.jceks
  fhir-config/src/test/java/com/ibm/fhir/config/test/ConfigurationServiceTest.java
  fhir-config/src/test/resources/fhirConfig.json
  fhir-connectathon-clients/src/test/resources/fhirkeys.jceks
  fhir-server-test/src/test/resources/fhirkeys.jceks
  fhir-server-webapp/src/main/webapp/WEB-INF/web.xml
  fhir-server/liberty-config/config/default/fhir-server-config.json
  fhir-server/liberty-config/resources/security/fhirkeys.jceks
  fhir-server/src/main/java/com/ibm/fhir/server/filter/enc/FHIRAesEncryptionFilter.java
  fhir-server/src/main/java/com/ibm/fhir/server/filter/enc/FHIRDecryptingInputStream.java
  fhir-server/src/main/java/com/ibm/fhir/server/filter/enc/FHIRDecryptingRequestWrapper.java
  fhir-server/src/main/java/com/ibm/fhir/server/filter/enc/FHIREncryptingOutputStream.java
  fhir-server/src/main/java/com/ibm/fhir/server/filter/enc/FHIREncryptingResponseWrapper.java
  fhir-server/src/main/java/com/ibm/fhir/server/resources/FHIRResource.java
Labels: automation, bug

#219 JavaDoc has some consistency changes needed #218
  fhir-connectathon-clients/src/test/java/com/ibm/fhir/connectathon/patient/PatientTrackTest.java
  fhir-model/src/test/java/com/ibm/fhir/model/spec/test/R4ExamplesDriver.java
  fhir-persistence/src/test/java/com/ibm/fhir/persistence/test/common/FHIRModelTestBase.java
  fhir-server-test/src/test/java/com/ibm/fhir/server/test/BundleTest.java
  fhir-server-test/src/test/java/com/ibm/fhir/server/test/FHIRToCdaOperationTest.java
  fhir-server-test/src/test/java/com/ibm/fhir/server/test/ServerSpecTest.java
  fhir-server-test/src/test/java/com/ibm/fhir/server/test/SimpleRouterTest.java
Labels: documentation

#215 fhir-bulkimportexport-webapp is not in the fhir-install dependency tree
  fhir-install/pom.xml
Labels: automation, bug

#216 WebSocket IT Fails intermittently #210
  fhir-server-test/src/test/java/com/ibm/fhir/server/test/FHIRServerTestBase.java
Labels: automation, bug

#228 issue #221 fix add_any_resource store procedure and the exception
  fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/dao/impl/ResourceDAONormalizedImpl.java
  fhir-persistence-schema/src/main/resources/add_any_resource.sql
Labels: automation, bug

#227 Manage M2E Settings for fhir-parent #206
  fhir-parent/pom.xml
Labels: automation, bug

#230 FHIR Validation Profile to Generate a Zip File #229
  fhir-validation/pom.xml
  fhir-validation/src/main/assembly/create-validation.md
  fhir-validation/src/main/assembly/distribution.xml
Labels: automation, enhancement

#231 issue #184 #210 websocket test timeout issue
  fhir-server-test/src/test/java/com/ibm/fhir/server/test/WebSocketNotificationsTest.java
Labels: bug

#234 FHIR Validation Profile to Generate a Zip File #229
  fhir-validation/src/main/assembly/distribution.xml
Labels: automation

#235 Web Socket Notification Test #210
  fhir-server-test/src/test/java/com/ibm/fhir/server/test/FHIRNotificationServiceClientEndpoint.java
  fhir-server-test/src/test/java/com/ibm/fhir/server/test/FHIRServerTestBase.java
  fhir-server-test/src/test/java/com/ibm/fhir/server/test/WebSocketNotificationsTest.java
  fhir-server-test/src/test/java/testng.xml
Labels: bug

#236 JavaDoc has some consistency changes needed #218
  fhir-client/src/main/java/com/ibm/fhir/client/FHIRRequestHeader.java
  fhir-config/src/main/java/com/ibm/fhir/config/PropertyGroup.java
  fhir-examples-generator/src/main/java/com/ibm/fhir/examples/plugin/ExamplesPlugin.java
  fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/model/BulkExportJobExecutionResponse.java
  fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/model/BulkExportJobInstanceRequest.java
  fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/model/BulkExportJobInstanceResponse.java
  fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/processor/BulkDataFactory.java
  fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/JDBCParameterBuilder.java
  fhir-search/src/main/java/com/ibm/fhir/search/util/SearchUtil.java
  fhir-search/src/main/java/com/ibm/fhir/search/valuetypes/impl/ValueTypesR4Impl.java
  fhir-tools/src/main/java/com/ibm/fhir/model/plugin/ModelPlugin.java
Labels: documentation

#243 Enable Spec Driver to use string values for TestTypes and Support switches in maven #242
  .github/workflows/build.yml
  fhir-model/src/test/java/com/ibm/fhir/model/spec/test/R4ExamplesDriver.java
  fhir-parent/pom.xml
  fhir-persistence-jdbc/src/test/java/com/ibm/fhir/persistence/jdbc/test/spec/R4JDBCExamplesTest.java
  fhir-server-test/src/test/java/com/ibm/fhir/server/test/WebSocketNotificationsTest.java
Labels: automation, bug

#245 Clean Cached Derby Data #244
  fhir-parent/pom.xml
  fhir-persistence-jdbc/pom.xml
  fhir-persistence-schema/pom.xml
Labels: enhancement

#251 Update announcement.md
  announcement.md
Labels: documentation

#271 Change name to IBM FHIR Server #114
  .github/ISSUE_TEMPLATE/release-checklist.md
  CONTRIBUTING.md
  MAINTAINERS.md
  docs/CHANGELOG.md
  docs/Conformance.md
  docs/DB2OnCloudSetup.md
  docs/FHIRServerUsersGuide.md
  docs/raspberry-pi-4/howto.md
  docs/template.md
  fhir-examples/src/main/resources/json/spec/LICENSE.md
  fhir-examples/src/main/resources/json/spec/README.md
  fhir-install/README.md
  fhir-install/src/main/resources/docs/README.txt
  fhir-parent/pom.xml
  fhir-persistence-schema/README.md
  fhir-search/src/main/resources/search-parameters.md
  fhir-server-test/src/test/java/com/ibm/fhir/cli/test/FHIRCliTest.java
  fhir-server-webapp/pom.xml
  fhir-server-webapp/src/main/webapp/WEB-INF/web.xml
  fhir-server/liberty-config-tenants/config/tenant2/readme.md
  fhir-server/liberty-config/config/default/extension-search-parameters-valuetypes.md
  fhir-server/liberty-config/config/default/extension-search-parameters.md
  fhir-server/liberty-config/server.xml
  fhir-server/pom.xml
  fhir-server/src/main/java/com/ibm/fhir/server/listener/FHIRServletContextListener.java
  fhir-server/src/main/java/com/ibm/fhir/server/resources/FHIRResource.java
  fhir-swagger-generator/src/main/java/com/ibm/fhir/openapi/generator/FHIROpenApiGenerator.java
  fhir-swagger-generator/src/main/java/com/ibm/fhir/swagger/generator/FHIRSwaggerGenerator.java
Labels: automation, documentation

#292 update fhir-validation assembly creation #291
  docs/create-fhir-validation-assembly.md
  fhir-validation/src/main/assembly/create-validation.md
Labels: documentation

#295 Update to reflect Search Parameters #203
  docs/FHIRSearchConfiguration.md
  docs/FHIRServerUsersGuide.md
Labels: documentation

#299 issue #294 support _summary for resource read
  fhir-operation/src/main/java/com/ibm/fhir/rest/FHIRResourceHelpers.java
  fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/impl/FHIRPersistenceJDBCImpl.java
  fhir-persistence/src/main/java/com/ibm/fhir/persistence/context/FHIRPersistenceContextFactory.java
  fhir-persistence/src/main/java/com/ibm/fhir/persistence/context/impl/FHIRPersistenceContextImpl.java
  fhir-server-test/src/test/java/com/ibm/fhir/server/test/ServerSpecTest.java
  fhir-server/src/main/java/com/ibm/fhir/server/resources/FHIRResource.java
Labels: enhancement

#302 Issue 204 - Update for Master (rarnold-performance)
  fhir-client/src/main/java/com/ibm/fhir/client/FHIRClient.java
  fhir-client/src/main/java/com/ibm/fhir/client/impl/FHIRClientImpl.java
  fhir-examples/src/main/resources/json/ibm.txt
  fhir-examples/src/main/resources/json/performance.txt
  fhir-model/src/test/java/com/ibm/fhir/model/spec/test/Analytics.java
  fhir-model/src/test/java/com/ibm/fhir/model/spec/test/AnalyticsTest.java
  fhir-model/src/test/java/com/ibm/fhir/model/spec/test/DriverMetrics.java
  fhir-model/src/test/java/com/ibm/fhir/model/spec/test/DriverStats.java
  fhir-model/src/test/java/com/ibm/fhir/model/spec/test/R4ExamplesDriver.java
  fhir-model/src/test/java/com/ibm/fhir/model/spec/test/ResponseTimes.java
  fhir-persistence-jdbc/src/test/java/com/ibm/fhir/persistence/jdbc/test/spec/CreateOperation.java
  fhir-persistence-jdbc/src/test/java/com/ibm/fhir/persistence/jdbc/test/spec/Main.java
  fhir-persistence-jdbc/src/test/java/com/ibm/fhir/persistence/jdbc/test/spec/R4JDBCExamplesProcessor.java
  fhir-persistence-jdbc/src/test/java/com/ibm/fhir/persistence/jdbc/test/spec/R4JDBCExamplesTest.java
  fhir-persistence-jdbc/src/test/java/com/ibm/fhir/persistence/jdbc/test/spec/ReadOperation.java
  fhir-persistence-schema/src/database/fhirdb/Dockerfile
  fhir-persistence-schema/src/database/fhirdb/create-database.sh
  fhir-persistence-schema/src/database/fhirdb/readme.md
  fhir-server-test/src/test/java/com/ibm/fhir/server/test/ExampleRequestProcessor.java
  fhir-server-test/src/test/java/com/ibm/fhir/server/test/FHIRServerTestBase.java
  fhir-server-test/src/test/java/com/ibm/fhir/server/test/R4ExampleServerTest.java
  fhir-server-test/src/test/java/com/ibm/fhir/server/test/app/Main.java
  fhir-server-test/src/test/java/com/ibm/fhir/server/test/app/NopProcessor.java
  fhir-server-test/src/test/java/com/ibm/fhir/server/test/app/TestContext.java
Labels: enhancement

#319 updates for build and deploy #145
  .gitignore
  docs/Build.mdx
  fhir-coverage-reports/.gitignore
  fhir-coverage-reports/pom.xml
  fhir-coverage-reports/src/main/java/.empty
  fhir-coverage-reports/src/main/resources/.empty
  fhir-coverage-reports/src/test/java/.empty
  fhir-coverage-reports/src/test/resources/.empty
  fhir-examples/pom.xml
  fhir-install/pom.xml
  fhir-install/src/main/assembly/jacoco-report.xml
  fhir-notification-websocket/pom.xml
  fhir-parent/pom.xml
  fhir-tools/dependency-reduced-pom.xml
  fhir-tools/pom.xml
Labels: automation, documentation

#323 update the parent dependencies for jackson libraries #322
  fhir-parent/pom.xml
Labels: automation
