Repository LinuxForHealth/FHIR, pull requests merged in 2019-12, with the labels that each got.

#451 Experimental Docker file is superceded by ./fhir-install/docker/Docke…
  fhir-persistence-schema/src/database/fhirdb/Dockerfile
  fhir-persistence-schema/src/database/fhirdb/create-database.sh
  fhir-persistence-schema/src/database/fhirdb/readme.md
Labels: automation

#452 clean up documentation to make tag visible #270
  fhir-install/README-DB2.md
Labels: documentation

#464 issue #462 #364 schema cleanup and add validation for r4jdbcexamplestest
  fhir-examples/src/main/resources/json/all.txt
  fhir-examples/src/main/resources/json/ibm.txt
  fhir-persistence-jdbc/src/test/java/com/ibm/fhir/persistence/jdbc/test/spec/R4JDBCExamplesTest.java
  fhir-persistence-schema/src/main/java/com/ibm/fhir/schema/control/FhirResourceGroup.java
  fhir-persistence-schema/src/main/resources/add_any_resource.sql
Labels: bug

#468 Issue #389 - re-enable FHIRPath spec tests
  fhir-path/src/main/java/com/ibm/fhir/path/evaluator/FHIRPathEvaluator.java
  fhir-path/src/test/resources/FHIRPath/tests-fhir-r4.xml
Labels: bug

#471 document java prereq
  docs/src/pages/guides/FHIRServerUsersGuide.md
Labels: documentation

#470 issue #460 - refactor R4ExamplesDriver to invoke tests as appropriate
  .github/workflows/build.yml
  fhir-benchmark/src/main/java/com/ibm/fhir/benchmark/FHIRValueSetBenchmarks.java
  fhir-benchmark/src/main/java/com/ibm/fhir/benchmark/util/BenchmarkUtil.java
  fhir-database-utils/src/main/java/com/ibm/fhir/database/utils/pool/PoolConnectionProvider.java
  fhir-examples/src/main/java/com/ibm/fhir/examples/ExamplesUtil.java
  fhir-examples/src/main/java/com/ibm/fhir/examples/Index.java
  fhir-examples/src/main/resources/all-json.txt
  fhir-examples/src/main/resources/all-xml.txt
  fhir-examples/src/main/resources/ibm-json.txt
  fhir-examples/src/main/resources/ibm-xml.txt
  fhir-examples/src/main/resources/json/all.txt
  fhir-examples/src/main/resources/json/ibm.txt
  fhir-examples/src/main/resources/json/minimal.txt
  fhir-examples/src/main/resources/json/performance.txt
  fhir-examples/src/main/resources/json/spec.txt
  fhir-examples/src/main/resources/minimal-json.txt
  fhir-examples/src/main/resources/minimal-xml.txt
  fhir-examples/src/main/resources/performance-json.txt
  fhir-examples/src/main/resources/spec-json.txt
  fhir-examples/src/main/resources/spec-xml.txt
  fhir-examples/src/main/resources/xml/all.txt
  fhir-examples/src/main/resources/xml/ibm.txt
  fhir-examples/src/main/resources/xml/minimal.txt
  fhir-examples/src/main/resources/xml/spec.txt
  fhir-model/pom.xml
  fhir-model/src/test/java/com/ibm/fhir/model/spec/test/R4ExamplesDriver.java
  fhir-model/src/test/java/com/ibm/fhir/model/spec/test/R4ExamplesTest.java
  fhir-model/src/test/java/com/ibm/fhir/model/test/TestUtil.java
  fhir-parent/pom.xml
  fhir-path/src/main/java/com/ibm/fhir/path/evaluator/FHIRPathEvaluator.java
  fhir-path/src/test/java/com/ibm/fhir/path/test/FHIRPathEvaluatorProfileTest.java
  fhir-path/src/test/java/com/ibm/fhir/path/test/NodeVisitorTest.java
  fhir-path/src/test/java/com/ibm/fhir/path/test/TypeFunctionTest.java
  fhir-persistence-jdbc/pom.xml
  fhir-persistence-jdbc/src/test/java/com/ibm/fhir/persistence/jdbc/test/spec/Main.java
  fhir-persistence-jdbc/src/test/java/com/ibm/fhir/persistence/jdbc/test/spec/R4JDBCExamplesTest.java
  fhir-search/pom.xml
  fhir-search/src/test/java/com/ibm/fhir/search/test/ExamplesDriverTest.java
  fhir-server-test/pom.xml
  fhir-server-test/src/test/java/com/ibm/fhir/server/test/R4ExampleServerTest.java
  fhir-server-test/src/test/java/com/ibm/fhir/server/test/app/Main.java
  fhir-validation/pom.xml
  fhir-validation/src/main/java/com/ibm/fhir/validation/FHIRValidator.java
  fhir-validation/src/test/java/com/ibm/fhir/validation/test/BundleValidationTest.java
  fhir-validation/src/test/java/com/ibm/fhir/validation/test/R4ExamplesValidatorTest.java
Labels: enhancement

#477 issue #469 fix open count issue for pooledconnection
  fhir-database-utils/src/main/java/com/ibm/fhir/database/utils/pool/PoolConnectionProvider.java
Labels: bug

#474 Number searches with implicit ranges #257
  fhir-examples/src/main/resources/json/ibm/basic/BasicNumber.json
  fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/JDBCConstants.java
  fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/impl/FHIRPersistenceJDBCImpl.java
  fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/JDBCQueryBuilder.java
  fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/type/NumberParmBehaviorUtil.java
  fhir-persistence-jdbc/src/test/java/com/ibm/fhir/persistence/jdbc/test/util/NumberParmBehaviorUtilTest.java
  fhir-persistence-jdbc/src/test/java/testng.xml
  fhir-persistence/src/test/java/com/ibm/fhir/persistence/search/test/AbstractSearchDateTest.java
  fhir-persistence/src/test/java/com/ibm/fhir/persistence/search/test/AbstractSearchNumberTest.java
  fhir-persistence/src/test/java/com/ibm/fhir/persistence/search/test/AbstractSearchQuantityTest.java
  fhir-persistence/src/test/java/com/ibm/fhir/persistence/search/test/AbstractSearchReferenceTest.java
  fhir-persistence/src/test/java/com/ibm/fhir/persistence/search/test/AbstractSearchStringTest.java
  fhir-persistence/src/test/java/com/ibm/fhir/persistence/search/test/AbstractSearchTokenTest.java
  fhir-persistence/src/test/java/com/ibm/fhir/persistence/search/test/AbstractSearchURITest.java
  fhir-persistence/src/test/resources/config/number/extension-search-parameters.json
  fhir-persistence/src/test/resources/logging.unitTest.properties
  fhir-search/src/main/java/com/ibm/fhir/search/parameters/ParameterValue.java
Labels: search

#492 Minor fix on line 08
  docs/readme.md
Labels: documentation

#490 Quantity searches update to consider implicit ranges #257
  fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/dao/api/ParameterDAO.java
  fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/dao/impl/ParameterDAOImpl.java
  fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/CodeSystemsCache.java
  fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/JDBCQueryBuilder.java
  fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/type/NumberParmBehaviorUtil.java
  fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/type/QuantityParmBehaviorUtil.java
  fhir-persistence-jdbc/src/test/java/com/ibm/fhir/persistence/jdbc/test/util/NumberParmBehaviorUtilTest.java
  fhir-persistence-jdbc/src/test/java/com/ibm/fhir/persistence/jdbc/test/util/QuantityParmBehaviorUtilTest.java
  fhir-persistence-jdbc/src/test/java/testng.xml
  fhir-persistence/src/test/java/com/ibm/fhir/persistence/search/test/AbstractSearchQuantityTest.java
Labels: enhancement, search

#489 issue #261 #494 whole system search enhancement and fix for self url of chained parameter search result
  fhir-cli/src/main/java/com/ibm/fhir/cli/invoker/SearchAllInvoker.java
  fhir-client/src/main/java/com/ibm/fhir/client/FHIRClient.java
  fhir-client/src/main/java/com/ibm/fhir/client/impl/FHIRClientImpl.java
  fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/QuerySegmentAggregator.java
  fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/QuerySegmentAggregatorFactory.java
  fhir-search/src/main/java/com/ibm/fhir/search/SearchConstants.java
  fhir-search/src/main/java/com/ibm/fhir/search/context/FHIRSearchContext.java
  fhir-search/src/main/java/com/ibm/fhir/search/context/impl/FHIRSearchContextImpl.java
  fhir-search/src/main/java/com/ibm/fhir/search/uri/UriBuilder.java
  fhir-search/src/main/java/com/ibm/fhir/search/util/SearchUtil.java
  fhir-server-test/src/test/java/com/ibm/fhir/server/test/FHIRDocumentOperationTest.java
  fhir-server-test/src/test/java/com/ibm/fhir/server/test/FHIROperationTest.java
  fhir-server-test/src/test/java/com/ibm/fhir/server/test/FHIRServerTestBase.java
  fhir-server-test/src/test/java/com/ibm/fhir/server/test/SearchAllTest.java
  fhir-server/src/main/java/com/ibm/fhir/server/resources/FHIRResource.java
Labels: enhancement, search

#500 issue #495 performance improvement
  fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/JDBCConstants.java
  fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/InclusionQuerySegmentAggregator.java
  fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/JDBCQueryBuilder.java
  fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/QuerySegmentAggregator.java
  fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/SortedQuerySegmentAggregator.java
  fhir-persistence-schema/src/main/java/com/ibm/fhir/schema/control/FhirResourceGroup.java
  fhir-server-test/src/test/java/com/ibm/fhir/server/test/SearchPerformanceTest.java
Labels: bug, search

#497 Support "special" search param Location-near #259
  docs/src/pages/guides/FHIRServerUsersGuide.md
  fhir-config/src/main/java/com/ibm/fhir/config/FHIRConfiguration.java
  fhir-model/src/main/java/com/ibm/fhir/model/visitor/DefaultVisitor.java
  fhir-model/src/main/java/com/ibm/fhir/model/visitor/Visitor.java
  fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/JDBCConstants.java
  fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/dao/impl/ParameterDAOImpl.java
  fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/dao/impl/ParameterVisitorBatchDAO.java
  fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/dto/Parameter.java
  fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/JDBCParameterBuildingVisitor.java
  fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/JDBCQueryBuilder.java
  fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/QuerySegmentAggregator.java
  fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/type/LocationParmBehaviorUtil.java
  fhir-persistence-jdbc/src/test/java/com/ibm/fhir/persistence/jdbc/search/test/JDBCSearchNearTest.java
  fhir-persistence-jdbc/src/test/java/com/ibm/fhir/persistence/jdbc/test/util/LocationParmBehaviorUtilTest.java
  fhir-persistence/src/main/java/com/ibm/fhir/persistence/util/AbstractQueryBuilder.java
  fhir-persistence/src/main/java/com/ibm/fhir/persistence/util/BoundingBox.java
  fhir-persistence/src/main/java/com/ibm/fhir/persistence/util/FHIRPersistenceUtil.java
  fhir-persistence/src/test/resources/logging.unitTest.properties
  fhir-search/README.md
  fhir-search/src/main/java/com/ibm/fhir/search/SearchConstants.java
  fhir-search/src/main/java/com/ibm/fhir/search/exception/SearchExceptionUtil.java
  fhir-search/src/main/java/com/ibm/fhir/search/location/NearLocationHandler.java
  fhir-search/src/main/java/com/ibm/fhir/search/location/bounding/Bounding.java
  fhir-search/src/main/java/com/ibm/fhir/search/location/bounding/BoundingBox.java
  fhir-search/src/main/java/com/ibm/fhir/search/location/bounding/BoundingRadius.java
  fhir-search/src/main/java/com/ibm/fhir/search/location/bounding/BoundingType.java
  fhir-search/src/main/java/com/ibm/fhir/search/location/uom/UOMManager.java
  fhir-search/src/main/java/com/ibm/fhir/search/location/uom/standard/ImperialUnits.java
  fhir-search/src/main/java/com/ibm/fhir/search/location/uom/standard/MetricUnits.java
  fhir-search/src/main/java/com/ibm/fhir/search/location/uom/standard/StatuteLengthUnits.java
  fhir-search/src/main/java/com/ibm/fhir/search/location/util/LocationUtil.java
  fhir-search/src/main/java/com/ibm/fhir/search/util/SearchUtil.java
  fhir-search/src/test/java/com/ibm/fhir/search/location/BoundingTest.java
  fhir-search/src/test/java/com/ibm/fhir/search/location/LocationUtilTest.java
  fhir-search/src/test/java/com/ibm/fhir/search/location/NearLocationHandlerBoundingBoxTest.java
  fhir-search/src/test/java/com/ibm/fhir/search/location/NearLocationHandlerBoundingRadiusTest.java
  fhir-search/src/test/java/com/ibm/fhir/search/location/UOMManagerTest.java
  fhir-server-test/src/test/java/com/ibm/fhir/server/test/SearchNearTest.java
  fhir-server-test/src/test/java/testng.xml
  fhir-tools/src/main/java/com/ibm/fhir/tools/CodeGenerator.java
Labels: enhancement, search

#516 Update readme.md
  docs/readme.md
  docs/src/pages/Conformance.md
Labels: documentation

#517 Search modifier refactoring and doc update
  docs/src/pages/Conformance.md
  fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/JDBCConstants.java
  fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/impl/FHIRPersistenceJDBCImpl.java
  fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/JDBCQueryBuilder.java
  fhir-search/src/main/java/com/ibm/fhir/search/SearchConstants.java
Labels: search

#506 Improve Date Time support and _lastUpdated behavior #255 #258 #437
  fhir-core/src/main/java/com/ibm/fhir/core/FHIRUtilities.java
  fhir-database-utils/src/main/java/com/ibm/fhir/database/utils/derby/DerbyMaster.java
  fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/JDBCConstants.java
  fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/dao/api/FHIRDbDAO.java
  fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/dao/api/ParameterDAO.java
  fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/dao/api/ResourceDAO.java
  fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/dao/impl/FHIRDbDAOImpl.java
  fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/dao/impl/ParameterVisitorBatchDAO.java
  fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/dao/impl/ResourceDAOImpl.java
  fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/derby/FhirRefSequenceDAOImpl.java
  fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/impl/FHIRPersistenceJDBCImpl.java
  fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/InclusionQuerySegmentAggregator.java
  fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/JDBCParameterBuildingVisitor.java
  fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/JDBCQueryBuilder.java
  fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/QueryBuilderUtil.java
  fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/QuerySegmentAggregator.java
  fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/SortedQuerySegmentAggregator.java
  fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/UriModifierUtil.java
  fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/type/DateParmBehaviorUtil.java
  fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/type/LastUpdatedParmBehaviorUtil.java
  fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/type/LocationParmBehaviorUtil.java
  fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/type/NumberParmBehaviorUtil.java
  fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/type/QuantityParmBehaviorUtil.java
  fhir-persistence-jdbc/src/test/java/com/ibm/fhir/persistence/jdbc/test/JDBCIncludeRevincludeTest.java
  fhir-persistence-jdbc/src/test/java/com/ibm/fhir/persistence/jdbc/test/util/CacheUtilTest.java
  fhir-persistence-jdbc/src/test/java/com/ibm/fhir/persistence/jdbc/test/util/DateParmBehaviorUtilTest.java
  fhir-persistence-jdbc/src/test/java/com/ibm/fhir/persistence/jdbc/test/util/LastUpdatedParmBehaviorUtilTest.java
  fhir-persistence-jdbc/src/test/java/com/ibm/fhir/persistence/jdbc/test/util/ParameterExtractionTest.java
  fhir-persistence-jdbc/src/test/java/com/ibm/fhir/persistence/jdbc/test/util/QueryBuilderUtilTest.java
  fhir-persistence-jdbc/src/test/java/com/ibm/fhir/persistence/jdbc/test/util/UriModifierUtilTest.java
  fhir-persistence-jdbc/src/test/java/testng.xml
  fhir-persistence/src/main/java/com/ibm/fhir/persistence/interceptor/FHIRPersistenceEvent.java
  fhir-persistence/src/main/java/com/ibm/fhir/persistence/util/AbstractQueryBuilder.java
  fhir-persistence/src/test/java/com/ibm/fhir/persistence/search/test/AbstractPLSearchTest.java
  fhir-persistence/src/test/java/com/ibm/fhir/persistence/search/test/AbstractSearchDateTest.java
  fhir-persistence/src/test/java/com/ibm/fhir/persistence/search/test/AbstractSearchReferenceTest.java
  fhir-persistence/src/test/java/com/ibm/fhir/persistence/search/test/AbstractWholeSystemSearchTest.java
  fhir-persistence/src/test/java/com/ibm/fhir/persistence/test/common/AbstractIncludeRevincludeTest.java
  fhir-search/src/main/java/com/ibm/fhir/search/date/DateTimeHandler.java
  fhir-search/src/main/java/com/ibm/fhir/search/exception/SearchExceptionUtil.java
  fhir-search/src/main/java/com/ibm/fhir/search/parameters/QueryParameter.java
  fhir-search/src/main/java/com/ibm/fhir/search/parameters/QueryParameterValue.java
  fhir-search/src/main/java/com/ibm/fhir/search/util/SearchUtil.java
  fhir-search/src/main/java/com/ibm/fhir/search/valuetypes/impl/ValueTypesR4Impl.java
  fhir-search/src/main/resources/valuetypes-default.json
  fhir-search/src/test/java/com/ibm/fhir/search/date/DateTimeHandlerTest.java
  fhir-server-test/src/test/java/com/ibm/fhir/server/test/SortingTest.java
Labels: bug, enhancement, search

#530 issue #528 - use server timezone to interpret dates
  docs/src/pages/Conformance.md
  fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/type/DateParmBehaviorUtil.java
  fhir-persistence/src/test/java/com/ibm/fhir/persistence/search/test/AbstractSearchDateTest.java
  fhir-search/src/main/java/com/ibm/fhir/search/date/DateTimeHandler.java
Labels: search

#529 issue #528 - update Conformance.md and tweak datetime precision
  docs/src/pages/Conformance.md
  fhir-examples/src/main/resources/json/ibm/basic/BasicDate.json
  fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/JDBCParameterBuildingVisitor.java
  fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/type/DateParmBehaviorUtil.java
  fhir-persistence/src/test/java/com/ibm/fhir/persistence/search/test/AbstractSearchDateTest.java
  fhir-persistence/src/test/java/com/ibm/fhir/persistence/test/common/AbstractPersistenceTest.java
  fhir-search/src/main/java/com/ibm/fhir/search/date/DateTimeHandler.java
  fhir-search/src/test/java/com/ibm/fhir/search/date/DateTimeHandlerTest.java
Labels: bug, search

#527 Set timezone to UTC for all storedprocedure timestamps
  docs/src/pages/Conformance.md
  fhir-core/src/main/java/com/ibm/fhir/core/FHIRUtilities.java
  fhir-examples/src/main/resources/json/ibm/basic/BasicDate.json
  fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/JDBCConstants.java
  fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/dao/impl/FHIRDbDAOImpl.java
  fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/dao/impl/ParameterVisitorBatchDAO.java
  fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/dao/impl/ResourceDAOImpl.java
  fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/derby/DerbyResourceDAO.java
  fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/dto/DateParmVal.java
  fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/JDBCParameterBuildingVisitor.java
  fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/type/DateParmBehaviorUtil.java
  fhir-persistence-jdbc/src/test/java/com/ibm/fhir/persistence/jdbc/test/util/DateParmBehaviorUtilTest.java
  fhir-persistence-jdbc/src/test/java/com/ibm/fhir/persistence/jdbc/test/util/LocationParmBehaviorUtilTest.java
  fhir-persistence/src/test/java/com/ibm/fhir/persistence/search/test/AbstractSearchDateTest.java
  fhir-persistence/src/test/java/com/ibm/fhir/persistence/test/common/AbstractPersistenceTest.java
  fhir-search/src/main/java/com/ibm/fhir/search/date/DateTimeHandler.java
  fhir-search/src/test/java/com/ibm/fhir/search/date/DateTimeHandlerTest.java
Labels: bug, search

#537 issue #535 - Deduplicate the SearchParameter map
  fhir-search/src/main/java/com/ibm/fhir/search/parameters/ParametersMap.java
  fhir-search/src/main/java/com/ibm/fhir/search/parameters/ParametersUtil.java
  fhir-search/src/main/java/com/ibm/fhir/search/parameters/cache/TenantSpecificSearchParameterCache.java
  fhir-search/src/main/java/com/ibm/fhir/search/util/SearchUtil.java
  fhir-search/src/test/java/com/ibm/fhir/search/parameters/MultiTenantSearchParameterTest.java
  fhir-search/src/test/java/com/ibm/fhir/search/parameters/ParametersSearchUtilTest.java
  fhir-search/src/test/java/com/ibm/fhir/search/parameters/ParametersUtilTest.java
Labels: search

#534 build and post latest javadocs #533
  fhir-operation/src/test/java/com/ibm/fhir/operation/test/CrashingOperation.java
Labels: automation, documentation

#539 Fix Site Automation
  .github/workflows/site.yml
Labels: automation, documentation

#540 Forcing a Site / Docs build
  docs/src/pages/index.mdx
Labels: automation, documentation

#526 Add dependency graph image to docs #523
  docs/images/fhir-dependency-graph.png
Labels: documentation
