Repository LinuxForHealth/FHIR, pull requests merged in 2019-09, with the labels that each got.

#12 Oauth wiki link fix
  docs/FHIRServerUsersGuide.md
Labels: documentation

#15 re-factored the code to remove unused internal resource types
  fhir-server-test/src/test/java/com/ibm/watson/health/fhir/cli/test/FHIRCliTest.java
  fhir-server-test/src/test/java/com/ibm/watson/health/fhir/server/test/ServerSpecTest.java
  fhir-server/src/main/java/com/ibm/watson/health/fhir/server/resources/FHIRResource.java
Labels: enhancement

#14 update the code for watsonhealth to watson/health or watson.health
  build/gen-code.sh
  docs/FHIRServerUsersGuide.md
  fhir-cli/src/main/resources/scripts/fhir-cli
  fhir-client/src/test/java/com/ibm/watson/health/fhir/client/test/mains/JaxrsClientTestMain.java
  fhir-connectathon-clients/src/test/java/com/ibm/watson/health/fhir/connectathon/patient/PatientTrackTest.java
  fhir-connectathon-clients/src/test/resources/patient.json
  fhir-connectathon-clients/src/test/resources/patientNoDiv.json
  fhir-model/src/main/java/com/ibm/watson/health/fhir/model/util/FHIRUtil.java
  fhir-operation-healthcheck/src/main/resources/healthcheck.json
  fhir-operation/src/test/resources/operationdefinition-bad.json
  fhir-persistence-jdbc/src/test/resources/config/date/extension-search-parameters.json
  fhir-persistence-jdbc/src/test/resources/config/default/extension-search-parameters.json
  fhir-persistence-jdbc/src/test/resources/config/number/extension-search-parameters.json
  fhir-persistence-jdbc/src/test/resources/config/quantity/extension-search-parameters.json
  fhir-persistence-jdbc/src/test/resources/config/reference/extension-search-parameters.json
  fhir-persistence-jdbc/src/test/resources/config/string/extension-search-parameters.json
  fhir-persistence-jdbc/src/test/resources/config/token/extension-search-parameters.json
  fhir-persistence-jdbc/src/test/resources/config/uri/extension-search-parameters.json
  fhir-persistence/src/test/java/com/ibm/watson/health/fhir/persistence/test/common/AbstractSearchAllTest.java
  fhir-replication-api/src/main/java/com/ibm/watson/health/fhir/replication/api/util/ReplicationUtil.java
  fhir-replication-api/src/test/resources/config/default/fhir-server-config.json
  fhir-search/src/test/java/com/ibm/watson/health/fhir/search/test/SearchTagTest.java
  fhir-search/src/test/java/com/ibm/watson/health/fhir/search/test/tools/ExtensionSearchTool.java
  fhir-search/src/test/java/com/ibm/watson/health/fhir/search/uri/test/UriTest.java
  fhir-search/src/test/resources/config/default/extension-search-parameters.json
  fhir-search/src/test/resources/config/tenant1/extension-search-parameters.json
  fhir-search/src/test/resources/config/tenant2/extension-search-parameters.json.hide1
  fhir-search/src/test/resources/config/tenant2/extension-search-parameters.json.hide2
  fhir-search/src/test/resources/config/tenant3/extension-search-parameters.json
  fhir-search/src/test/resources/config/tenant4/extension-search-parameters.json
  fhir-search/src/test/resources/config/tenant5/extension-search-parameters.json
  fhir-search/src/test/resources/testdata/extract/tag-test.json
  fhir-server-test/src/test/java/com/ibm/watson/health/fhir/cli/test/FHIRCliTest.java
  fhir-server-test/src/test/java/com/ibm/watson/health/fhir/server/test/Base64BinaryTest.java
  fhir-server-test/src/test/java/com/ibm/watson/health/fhir/server/test/SearchAllTest.java
  fhir-server-test/src/test/java/com/ibm/watson/health/fhir/server/test/SearchExtensionsTest.java
  fhir-server-test/src/test/java/com/ibm/watson/health/fhir/server/test/ServerSpecTest.java
  fhir-server/liberty-config-tenants/config/tenant1/extension-search-parameters.json
  fhir-server/liberty-config-tenants/config/tenant1/schematron/patient.sch
  fhir-server/liberty-config-tenants/config/tenant2/readme.md
  fhir-server/liberty-config/config/default/extension-search-parameters.md
  fhir-server/src/main/java/com/ibm/watson/health/fhir/server/resources/FHIRResource.java
Labels: enhancement

#24 On startup, the userlib is required for derbySproc #23
  fhir-server/src/main/java/com/ibm/watson/health/fhir/server/listener/FHIRServletContextListener.java
Labels: bug

#25 _format parameter overrides the HTTP Header Accept #542
  fhir-server-test/src/test/java/com/ibm/watson/health/fhir/server/test/BasicServerTest.java
  fhir-server/liberty-config/server.xml
  fhir-server/src/main/java/com/ibm/watson/health/fhir/server/filter/rest/FHIRHttpServletRequestWrapper.java
Labels: bug, enhancement

#42 Implement $apply for PlanDefinition/CarePlan #38
  fhir-operation-apply/.gitignore
  fhir-operation-apply/pom.xml
  fhir-operation-apply/src/main/java/com/ibm/watson/health/fhir/operation/apply/ApplyOperation.java
  fhir-operation-apply/src/main/resources/META-INF/services/com.ibm.watson.health.fhir.operation.FHIROperation
  fhir-operation-apply/src/main/resources/apply.json
  fhir-operation-apply/src/test/java/.empty
  fhir-operation-apply/src/test/resources/.empty
  fhir-operation/src/main/java/com/ibm/watson/health/fhir/operation/util/FHIROperationUtil.java
  fhir-parent/pom.xml
  fhir-server-test/src/test/java/com/ibm/watson/health/fhir/server/test/PlanDefinitionApplyOperationTest.java
  fhir-server-test/src/test/resources/testdata/ActivityDefinition-1.json
  fhir-server-test/src/test/resources/testdata/ActivityDefinition-2.json
  fhir-server-test/src/test/resources/testdata/PlanDefinition-1.json
  fhir-server-webapp/pom.xml
Labels: enhancement

#86 fix for ear creation #57
  fhir-core/pom.xml
  fhir-notification/pom.xml
  fhir-operation-apply/pom.xml
  fhir-operation/pom.xml
  fhir-persistence/pom.xml
  fhir-provider/pom.xml
  fhir-server/pom.xml
Labels: bug

#85 Enable Travis for the `FHIR` Repository #13
  MAINTAINERS.md
  README.md
Labels: documentation

#123 Add note for issue 114 package name change
  README.md
Labels: documentation

#135 issue #131 change validation response to 200 for invalid resources
  fhir-operation-validate/src/main/java/com/ibm/fhir/operation/validate/ValidateOperation.java
  fhir-server-test/src/test/java/com/ibm/fhir/server/test/FHIRValidateOperationTest.java
Labels: bug

#144 issue #101 use null instead of empty continuetoken for s3
  fhir-bulkimportexport-webapp/src/main/java/com/ibm/fhir/bulkimport/BulkImportBatchLet.java
  fhir-bulkimportexport-webapp/src/main/java/com/ibm/fhir/bulkimport/ChunkReader.java
Labels: bug

#148 issue #13 - upload server test results to facilitate debug
  .github/workflows/build.yml
  build/post-integration-test.sh
Labels: automation

#150 Fix issue with benchmark finding the right dependencies #141
  fhir-benchmark/pom.xml
Labels: automation

#143 issue #13 - enable travis and automation
  .travis.yml
  build/.gitignore
  build/bintray-config.template
  build/git-build.sh
  build/push-javadoc-to-gh-pages.sh
  build/sync2MC.sh
  fhir-bulkimportexport-webapp/pom.xml
  fhir-cli/pom.xml
  fhir-coverage-reports/pom.xml
  fhir-examples/pom.xml
  fhir-install/pom.xml
  fhir-parent/checkstyle.xml
  fhir-parent/pom.xml
  fhir-persistence-proxy/pom.xml
  fhir-server-test/src/test/java/com/ibm/fhir/server/test/WebSocketNotificationsTest.java
Labels: automation
