Repository LinuxForHealth/FHIR, pull requests merged in 2019-11, with the labels that each got.

#363 #362 - address issue with unbalanced parameters and update the stored…
  fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/dao/impl/ResourceDAOImpl.java
  fhir-persistence-schema/src/main/java/com/ibm/fhir/schema/control/FhirResourceGroup.java
  fhir-persistence-schema/src/main/resources/add_any_resource.sql
Labels: bug

#378 issue #377 changes for the db schema tool
  fhir-database-utils/src/main/java/com/ibm/fhir/database/utils/api/IDatabaseAdapter.java
  fhir-database-utils/src/main/java/com/ibm/fhir/database/utils/api/IDatabaseTypeAdapter.java
  fhir-database-utils/src/main/java/com/ibm/fhir/database/utils/db2/Db2Adapter.java
  fhir-database-utils/src/main/java/com/ibm/fhir/database/utils/derby/DerbyAdapter.java
  fhir-persistence-schema/src/main/java/com/ibm/fhir/schema/app/Main.java
Labels: bug

#379 Update README.md
  fhir-persistence-schema/README.md
Labels: documentation

#371 No schema files #159
  fhir-persistence-schema/README.md
  fhir-persistence-schema/src/main/java/com/ibm/fhir/schema/app/SchemaPrinter.java
  fhir-persistence-schema/src/main/java/com/ibm/fhir/schema/app/SimpleSchemaPrinter.java
Labels: automation, documentation

#408 fix logging for SearchUtil extractParametersValues #255
  fhir-search/src/main/java/com/ibm/fhir/search/util/SearchUtil.java
Labels: bug

#407 Javadocs #145
  fhir-examples/pom.xml
  fhir-parent/pom.xml
  fhir-parent/src/javadocs/stylesheet.css
  fhir-tools/pom.xml
Labels: documentation

#413 issue #140 db2 docker for server integration test
  fhir-install/README-DB2.md
  fhir-install/docker/Dockerfile-fhirdb2
  fhir-install/docker/create-database.sh
Labels: automation

#423 issue #396 fix for derby dead lock issue
  fhir-persistence-schema/src/main/java/com/ibm/fhir/schema/control/FhirResourceGroup.java
Labels: bug, schema

#432 issue #426 fix for pipeline derby jdbc test error
  fhir-database-utils/src/main/java/com/ibm/fhir/database/utils/derby/DerbyMaster.java
  fhir-persistence-jdbc/src/test/java/com/ibm/fhir/persistence/jdbc/test/spec/R4JDBCExamplesTest.java
  fhir-persistence/src/test/java/com/ibm/fhir/persistence/test/common/AbstractPersistenceTest.java
Labels: bug

#436 add automation to support the automatic generation of the website #435
  .github/workflows/site.yml
  docs/package.json
  docs/src/data/nav-items.yaml
  docs/src/gatsby-theme-carbon/components/LeftNav/ResourceLinks.js
Labels: automation

#439 Issue 438
  fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/dao/api/ResourceDAO.java
  fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/dao/impl/ResourceDAOImpl.java
  fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/InclusionQuerySegmentAggregator.java
  fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/JDBCQueryBuilder.java
  fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/QuerySegmentAggregator.java
  fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/SortedQuerySegmentAggregator.java
  fhir-persistence/src/test/resources/logging.unitTest.properties
Labels: enhancement

#443 Updates to search sort for R4 #256
  fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/JDBCQueryBuilder.java
  fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/QuerySegmentAggregator.java
  fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/SortedQuerySegmentAggregator.java
  fhir-persistence/src/main/java/com/ibm/fhir/persistence/MultiResourceResult.java
  fhir-persistence/src/main/java/com/ibm/fhir/persistence/util/AbstractQueryBuilder.java
  fhir-persistence/src/test/java/com/ibm/fhir/persistence/test/common/AbstractPersistenceTest.java
  fhir-persistence/src/test/java/com/ibm/fhir/persistence/test/common/AbstractSortTest.java
  fhir-search/src/main/java/com/ibm/fhir/search/SearchConstants.java
  fhir-search/src/main/java/com/ibm/fhir/search/context/FHIRSearchContext.java
  fhir-search/src/main/java/com/ibm/fhir/search/exception/SearchExceptionUtil.java
  fhir-search/src/main/java/com/ibm/fhir/search/parameters/Parameter.java
  fhir-search/src/main/java/com/ibm/fhir/search/parameters/SortParameter.java
  fhir-search/src/main/java/com/ibm/fhir/search/sort/Sort.java
  fhir-search/src/main/java/com/ibm/fhir/search/uri/UriBuilder.java
  fhir-search/src/main/java/com/ibm/fhir/search/util/SearchUtil.java
  fhir-search/src/main/java/com/ibm/fhir/search/valuetypes/impl/ValueTypesR4Impl.java
  fhir-search/src/test/java/com/ibm/fhir/search/sort/test/SortParameterParseTest.java
  fhir-search/src/test/java/com/ibm/fhir/search/sort/test/SortParameterTest.java
  fhir-search/src/test/java/com/ibm/fhir/search/sort/test/SortTest.java
  fhir-search/src/test/java/com/ibm/fhir/search/sort/test/SortUriTest.java
  fhir-search/src/test/java/com/ibm/fhir/search/test/CompartmentParseQueryParmsTest.java
  fhir-server-test/src/test/java/com/ibm/fhir/server/test/SortingTest.java
Labels: enhancement, search

#445 issue #103 #105 bulkdataExport multi-resType support with Res counts
  fhir-bulkimportexport-webapp/src/main/java/com/ibm/fhir/bulkexport/CheckPointAlgorithm.java
  fhir-bulkimportexport-webapp/src/main/java/com/ibm/fhir/bulkexport/CheckPointUserData.java
  fhir-bulkimportexport-webapp/src/main/java/com/ibm/fhir/bulkexport/ChunkReader.java
  fhir-bulkimportexport-webapp/src/main/java/com/ibm/fhir/bulkexport/ChunkWriter.java
  fhir-bulkimportexport-webapp/src/main/java/com/ibm/fhir/bulkexport/TransientUserData.java
  fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/client/BulkDataClient.java
  fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/model/BulkExportJobExecutionResponse.java
  fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/model/PollingLocationResponse.java
  fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/processor/impl/CosExportImpl.java
  fhir-operation-bulkdata/src/test/java/com/ibm/fhir/operation/bulkdata/model/PollingLocationResponseTest.java
Labels: enhancement

#446 Issue #389 - updated FHIRPath engine per spec tests
  fhir-model/src/main/java/com/ibm/fhir/model/path/ClassInfo.java
  fhir-model/src/main/java/com/ibm/fhir/model/path/FHIRPathBooleanValue.java
  fhir-model/src/main/java/com/ibm/fhir/model/path/FHIRPathDateTimeValue.java
  fhir-model/src/main/java/com/ibm/fhir/model/path/FHIRPathDateValue.java
  fhir-model/src/main/java/com/ibm/fhir/model/path/FHIRPathDecimalValue.java
  fhir-model/src/main/java/com/ibm/fhir/model/path/FHIRPathIntegerValue.java
  fhir-model/src/main/java/com/ibm/fhir/model/path/FHIRPathNumberValue.java
  fhir-model/src/main/java/com/ibm/fhir/model/path/FHIRPathQuantityNode.java
  fhir-model/src/main/java/com/ibm/fhir/model/path/FHIRPathQuantityValue.java
  fhir-model/src/main/java/com/ibm/fhir/model/path/FHIRPathStringValue.java
  fhir-model/src/main/java/com/ibm/fhir/model/path/FHIRPathTemporalValue.java
  fhir-model/src/main/java/com/ibm/fhir/model/path/FHIRPathTimeValue.java
  fhir-model/src/main/java/com/ibm/fhir/model/path/FHIRPathType.java
  fhir-model/src/main/java/com/ibm/fhir/model/path/FHIRPathTypeInfoNode.java
  fhir-model/src/main/java/com/ibm/fhir/model/path/SimpleTypeInfo.java
  fhir-model/src/main/java/com/ibm/fhir/model/path/TypeInfo.java
  fhir-model/src/main/java/com/ibm/fhir/model/path/evaluator/FHIRPathEvaluator.java
  fhir-model/src/main/java/com/ibm/fhir/model/path/function/ChildrenFunction.java
  fhir-model/src/main/java/com/ibm/fhir/model/path/function/ConformsToFunction.java
  fhir-model/src/main/java/com/ibm/fhir/model/path/function/DescendantsFunction.java
  fhir-model/src/main/java/com/ibm/fhir/model/path/function/EndsWithFunction.java
  fhir-model/src/main/java/com/ibm/fhir/model/path/function/ExtensionFunction.java
  fhir-model/src/main/java/com/ibm/fhir/model/path/function/FirstFunction.java
  fhir-model/src/main/java/com/ibm/fhir/model/path/function/LastFunction.java
  fhir-model/src/main/java/com/ibm/fhir/model/path/function/NotFunction.java
  fhir-model/src/main/java/com/ibm/fhir/model/path/function/SingleFunction.java
  fhir-model/src/main/java/com/ibm/fhir/model/path/function/SkipFunction.java
  fhir-model/src/main/java/com/ibm/fhir/model/path/function/SubstringFunction.java
  fhir-model/src/main/java/com/ibm/fhir/model/path/function/TailFunction.java
  fhir-model/src/main/java/com/ibm/fhir/model/path/function/TakeFunction.java
  fhir-model/src/main/java/com/ibm/fhir/model/path/function/UnionFunction.java
  fhir-model/src/main/java/com/ibm/fhir/model/path/util/FHIRPathUtil.java
  fhir-model/src/test/java/com/ibm/fhir/model/path/test/FHIRPathSpecTest.java
  fhir-model/src/test/resources/FHIRPath/tests-fhir-r4.xml
  fhir-validation/src/main/java/com/ibm/fhir/validation/FHIRValidator.java
Labels: bug

#444 Support _pretty query parameter #269
  docs/src/pages/Conformance.md
  fhir-provider/src/main/java/com/ibm/fhir/provider/FHIRProvider.java
  fhir-provider/src/test/java/com/ibm/fhir/provider/FHIRProviderTest.java
  fhir-search/src/main/java/com/ibm/fhir/search/SearchConstants.java
  fhir-server-test/src/test/java/com/ibm/fhir/server/test/PrettyServerFormatTest.java
Labels: enhancement

#449 Issue 448
  docs/src/pages/Conformance.md
  fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/JDBCQueryBuilder.java
  fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/UriModifierUtil.java
  fhir-persistence-jdbc/src/test/java/com/ibm/fhir/persistence/jdbc/test/util/UriModifierUtilTest.java
  fhir-persistence/src/test/java/com/ibm/fhir/persistence/search/test/AbstractSearchURITest.java
  fhir-search/src/main/java/com/ibm/fhir/search/SearchConstants.java
  fhir-server-test/src/test/java/com/ibm/fhir/server/test/SearchExtensionsTest.java
Labels: search

#447 URI should default to complete match (not starts-with) #273
  docs/src/pages/Conformance.md
  fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/JDBCQueryBuilder.java
  fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/UriModifierUtil.java
  fhir-persistence-jdbc/src/test/java/com/ibm/fhir/persistence/jdbc/search/test/JDBCSearchURITest.java
  fhir-persistence-jdbc/src/test/java/com/ibm/fhir/persistence/jdbc/test/util/UriModifierUtilTest.java
  fhir-persistence/src/test/java/com/ibm/fhir/persistence/search/test/AbstractSearchURITest.java
  fhir-search/src/main/java/com/ibm/fhir/search/SearchConstants.java
  fhir-server-test/src/test/java/com/ibm/fhir/server/test/SearchExtensionsTest.java
Labels: bug, search
