Repository LinuxForHealth/FHIR, pull requests merged in 2020-06, with the labels that each got.

#1174 Issue #1172 - introduced fhir-operation-term module
  fhir-model/src/main/java/com/ibm/fhir/model/util/ModelSupport.java
  fhir-operation-term/pom.xml
  fhir-operation-term/src/main/java/com/ibm/fhir/operation/term/AbstractTermOperation.java
  fhir-operation-term/src/main/java/com/ibm/fhir/operation/term/ClosureOperation.java
  fhir-operation-term/src/main/java/com/ibm/fhir/operation/term/CodeSystemValidateCodeOperation.java
  fhir-operation-term/src/main/java/com/ibm/fhir/operation/term/ExpandOperation.java
  fhir-operation-term/src/main/java/com/ibm/fhir/operation/term/LookupOperation.java
  fhir-operation-term/src/main/java/com/ibm/fhir/operation/term/SubsumesOperation.java
  fhir-operation-term/src/main/java/com/ibm/fhir/operation/term/TranslateOperation.java
  fhir-operation-term/src/main/java/com/ibm/fhir/operation/term/ValueSetValidateCodeOperation.java
  fhir-operation-term/src/main/resources/META-INF/services/com.ibm.fhir.operation.FHIROperation
  fhir-operation/src/main/java/com/ibm/fhir/operation/registry/FHIROperationRegistry.java
  fhir-parent/pom.xml
  fhir-server-webapp/pom.xml
  fhir-term/src/main/java/com/ibm/fhir/term/service/FHIRTermService.java
  fhir-term/src/main/java/com/ibm/fhir/term/service/provider/DefaultTermServiceProvider.java
  fhir-term/src/main/java/com/ibm/fhir/term/spi/FHIRTermServiceProvider.java
  fhir-term/src/main/java/com/ibm/fhir/term/util/ConceptMapSupport.java
  fhir-term/src/test/java/com/ibm/fhir/term/service/test/FHIRTermServiceTest.java
Labels: new-module

#1204 Fix for Site Build Issue
  .github/workflows/site.yml
  docs/gatsby-config.js
  docs/package-lock.json
  docs/package.json
  docs/src/gatsby-theme-carbon/components/Layout.js
  docs/src/pages/guides/FHIRModelGuide.mdx
  docs/src/pages/guides/FHIRTerminologyGuide.md
Labels: automation

#1208 Fix for Mobile
  docs/gatsby-config.js
  docs/src/gatsby-theme-carbon/components/Banner.module.scss
  docs/src/gatsby-theme-carbon/components/Header.js
  docs/src/gatsby-theme-carbon/components/Header/Header.js
  docs/src/gatsby-theme-carbon/components/Header/Header.module.scss
  docs/src/gatsby-theme-carbon/components/HomepageBanner.js
  docs/src/gatsby-theme-carbon/components/Layout.js
  docs/src/gatsby-theme-carbon/templates/Homepage.module.scss
Labels: automation

#1233 Fix for Maven Wagon Pool failures, add a retry
  .github/workflows/build.yml
  .github/workflows/javadocs.yml
  build/release/build.sh
  build/release/check-dependency-security.sh
  build/release/clean.sh
  build/release/code-coverage.sh
  build/release/docker-push.sh
  build/release/release.sh
Labels: automation

#1234 Issue 876 - Postgres SQL Automation
  .github/workflows/persistence.yml
  build/persistence/.gitignore
  build/persistence/README.md
  build/persistence/bin/gather-logs.sh
  build/persistence/bin/integration-test.sh
  build/persistence/bin/post-integration-test.sh
  build/persistence/bin/pre-integration-test.sh
  build/persistence/bin/setup-prerequisites.sh
  build/persistence/postgres/.gitignore
  build/persistence/postgres/Dockerfile
  build/persistence/postgres/README.md
  build/persistence/postgres/docker-compose.yml
  build/persistence/postgres/post-integration-test.sh
  build/persistence/postgres/pre-integration-test.sh
  build/persistence/postgres/resources/db.sql
  build/persistence/postgres/resources/docker-entrypoint.sh
  fhir-server/liberty-config/config/default/fhir-server-config-postgresql.json
Labels: automation

#1269 Add Upload for two zip files outside of the loop
  .github/workflows/build.yml
  build/release/release.sh
Labels: ci-skip

#1275 All subsection links are broken in the FHIR Server User's Guide #1261
  docs/src/gatsby-theme-carbon/components/AutolinkHeader/AutolinkHeader.js
  docs/src/gatsby-theme-carbon/components/AutolinkHeader/AutolinkHeader.module.scss
Labels: automation

#1287 Fixed typo in xml snippet
  docs/src/pages/guides/FHIRServerUsersGuide.md
Labels: documentation
