Repository LinuxForHealth/FHIR, pull requests merged in 2020-04, with the labels that each got.

#883 Update for 4.1.0 Release
  .github/workflows/javadocs.yml
  fhir-database-utils/src/main/java/com/ibm/fhir/database/utils/derby/DerbyMaster.java
  fhir-database-utils/src/main/java/com/ibm/fhir/database/utils/model/Sequence.java
  fhir-persistence-jdbc/src/test/java/com/ibm/fhir/persistence/jdbc/test/spec/R4JDBCExamplesProcessor.java
  fhir-persistence-jdbc/src/test/java/com/ibm/fhir/persistence/jdbc/test/spec/R4JDBCExamplesTest.java
  fhir-persistence-jdbc/src/test/java/com/ibm/fhir/persistence/jdbc/test/util/DerbyInitializer.java
  fhir-persistence-jdbc/src/test/java/com/ibm/fhir/persistence/jdbc/test/util/NumberParmBehaviorUtilTest.java
  fhir-persistence-schema/src/main/java/com/ibm/fhir/schema/derby/DerbyFhirDatabase.java
Labels: automation, bug

#887 Clarifying $healthcheck
  docs/src/pages/guides/FHIRServerUsersGuide.md
Labels: documentation

#885 Fixup for 4.1.0 Site / Javadoc Release
  .github/workflows/javadocs.yml
  .github/workflows/javadocs_force_build.txt
  .github/workflows/release.yml
Labels: automation

#886 Update Snapshot for Release 4.1.0
  fhir-audit/pom.xml
  fhir-benchmark/pom.xml
  fhir-benchmark/src/main/java/com/ibm/fhir/benchmark/ObjectSizeEstimator.java
  fhir-bulkimportexport-webapp/pom.xml
  fhir-cli/pom.xml
  fhir-client/pom.xml
  fhir-config/pom.xml
  fhir-core/pom.xml
  fhir-database-utils/pom.xml
  fhir-examples-generator/pom.xml
  fhir-examples-generator/src/test/resources/examplesplugin/pom.xml
  fhir-examples/pom.xml
  fhir-ig-carin-bb/pom.xml
  fhir-ig-mcode/pom.xml
  fhir-ig-us-core/pom.xml
  fhir-install/pom.xml
  fhir-model/pom.xml
  fhir-notification-kafka/pom.xml
  fhir-notification-websocket/pom.xml
  fhir-notification/pom.xml
  fhir-openapi/pom.xml
  fhir-operation-apply/pom.xml
  fhir-operation-bulkdata/pom.xml
  fhir-operation-convert/pom.xml
  fhir-operation-document/pom.xml
  fhir-operation-healthcheck/pom.xml
  fhir-operation-validate/pom.xml
  fhir-operation/pom.xml
  fhir-parent/pom.xml
  fhir-path/pom.xml
  fhir-persistence-jdbc/pom.xml
  fhir-persistence-proxy/pom.xml
  fhir-persistence-schema/pom.xml
  fhir-persistence/pom.xml
  fhir-profile/pom.xml
  fhir-provider/pom.xml
  fhir-registry/pom.xml
  fhir-search/pom.xml
  fhir-server-test/pom.xml
  fhir-server-webapp/pom.xml
  fhir-server/pom.xml
  fhir-swagger-generator/pom.xml
  fhir-tools/dependency-reduced-pom.xml
  fhir-tools/pom.xml
  fhir-tools/src/test/resources/modelplugin/pom.xml
  fhir-validation/pom.xml
Labels: automation

#892 Update DB2OnCloudSetup.md #893
  docs/src/pages/guides/DB2OnCloudSetup.md
Labels: documentation

#897 issue #823 - documented extended operations in Conformance.md
  docs/src/pages/Conformance.md
  fhir-config/src/main/java/com/ibm/fhir/config/FHIRRequestContext.java
Labels: documentation

#922 issue #941 - force the use of TLSv1.2
  fhir-server/liberty-config/jvm.options
  fhir-server/liberty-config/server.xml
Labels: automation, security

#925 Update CreateFHIRValidationAssembly.md
  docs/src/pages/guides/CreateFHIRValidationAssembly.md
  fhir-validation/pom.xml
Labels: automation, documentation

#942 issue #941 aggregate in-fly metrics across all the partitions
  .github/workflows/build.yml
  fhir-bulkimportexport-webapp/src/main/java/com/ibm/fhir/bulkimport/ImportPartitionAnalyzer.java
  fhir-bulkimportexport-webapp/src/main/java/com/ibm/fhir/bulkimport/ImportPartitionCollector.java
Labels: bug

#940 Bulk-Data Import Operation and API #671
  .github/workflows/build.yml
  docs/src/pages/guides/FHIRServerUsersGuide.md
  fhir-bulkimportexport-webapp/src/main/java/com/ibm/fhir/bulkimport/ChunkWriter.java
  fhir-bulkimportexport-webapp/src/main/java/com/ibm/fhir/bulkimport/ImportPartitionMapper.java
  fhir-config/src/main/java/com/ibm/fhir/config/FHIRConfiguration.java
  fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/BulkDataConstants.java
  fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/ExportOperation.java
  fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/ImportOperation.java
  fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/StatusOperation.java
  fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/client/BulkDataClient.java
  fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/config/BulkDataConfigUtil.java
  fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/model/JobExecutionResponse.java
  fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/model/JobInstanceRequest.java
  fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/model/JobInstanceResponse.java
  fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/model/PollingLocationResponse.java
  fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/model/type/Input.java
  fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/model/type/JobParameter.java
  fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/model/type/StorageDetail.java
  fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/processor/BulkDataFactory.java
  fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/processor/ExportImportBulkData.java
  fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/processor/impl/CosExportImpl.java
  fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/processor/impl/DummyImportExportImpl.java
  fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/util/BulkDataExportUtil.java
  fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/util/BulkDataImportUtil.java
  fhir-operation-bulkdata/src/main/resources/META-INF/services/com.ibm.fhir.operation.FHIROperation
  fhir-operation-bulkdata/src/main/resources/import.json
  fhir-operation-bulkdata/src/main/resources/status.json
  fhir-operation-bulkdata/src/test/java/com/ibm/fhir/operation/bulkdata/BulkdataOperationTest.java
  fhir-operation-bulkdata/src/test/java/com/ibm/fhir/operation/bulkdata/model/BulkExportJobRestTest.java
  fhir-operation-bulkdata/src/test/java/com/ibm/fhir/operation/bulkdata/model/ImportsTest.java
  fhir-operation-bulkdata/src/test/java/com/ibm/fhir/operation/bulkdata/model/PollingLocationResponseTest.java
  fhir-operation-bulkdata/src/test/java/com/ibm/fhir/operation/bulkdata/processor/DummyImportExportImplTest.java
  fhir-operation-bulkdata/src/test/java/com/ibm/fhir/operation/bulkdata/util/BulkDataExportUtilTest.java
  fhir-operation-bulkdata/src/test/java/com/ibm/fhir/operation/bulkdata/util/BulkDataImportUtilTest.java
  fhir-operation-bulkdata/src/test/java/com/ibm/fhir/operation/support/bulkdata/helpers/ImportOperationDefinitionGenerator.java
  fhir-operation-bulkdata/src/test/java/com/ibm/fhir/operation/support/bulkdata/helpers/ImportOperationParametersGenerator.java
  fhir-operation-bulkdata/src/test/resources/testdata/config/default/bulkdata.json
  fhir-operation-bulkdata/src/test/resources/testdata/config/default/fhir-server-config.json
  fhir-operation-bulkdata/src/test/resources/testdata/config/dummy/bulkdata.json
  fhir-operation-bulkdata/src/test/resources/testdata/config/french/bulkdata.json.missing
  fhir-operation-bulkdata/src/test/resources/testdata/config/tenant1/.empty
  fhir-operation-bulkdata/src/test/resources/testdata/config/tenant2/bulkdata.json
  fhir-operation-bulkdata/src/test/resources/testdata/config/tenant3/bulkdata.json
  fhir-operation-bulkdata/src/test/resources/testdata/import/import-demo-bad-format.json
  fhir-operation-bulkdata/src/test/resources/testdata/import/import-demo-bad-format2.json
  fhir-operation-bulkdata/src/test/resources/testdata/import/import-demo-bad-format3.json
  fhir-operation-bulkdata/src/test/resources/testdata/import/import-demo-empty.json
  fhir-operation-bulkdata/src/test/resources/testdata/import/import-demo.json
  fhir-operation-bulkdata/src/test/resources/testdata/import/smart-on-fhir-import-example-parameters.json
  fhir-operation-bulkdata/src/test/resources/testdata/import/smart-on-fhir-import-example.json
  fhir-operation/src/main/java/com/ibm/fhir/operation/AbstractOperation.java
  fhir-server-test/src/test/java/com/ibm/fhir/server/test/ExportOperationTest.java
  fhir-server-test/src/test/java/com/ibm/fhir/server/test/ImportOperationTest.java
  fhir-server-test/src/test/resources/testdata/import-operation/test-import.ndjson
  fhir-server/liberty-config/config/default/fhir-server-config-db2.json
  fhir-server/liberty-config/config/default/fhir-server-config.json
  fhir-server/liberty-config/resources/security/fhirTruststore.jks
Labels: bug, documentation, enhancement

#963 issue #877 add max_prepared_transactions in user guide for postgresql
  docs/src/pages/guides/FHIRServerUsersGuide.md
Labels: documentation

#967 Fix for JKS to PKCS12 change
  fhir-bulkimportexport-webapp/src/main/java/com/ibm/fhir/bulkcommon/BulkDataUtils.java
  fhir-bulkimportexport-webapp/src/main/java/com/ibm/fhir/bulkexport/system/ChunkWriter.java
  fhir-bulkimportexport-webapp/src/main/java/com/ibm/fhir/bulkimport/ChunkReader.java
  fhir-bulkimportexport-webapp/src/main/java/com/ibm/fhir/bulkimport/ChunkWriter.java
  fhir-bulkimportexport-webapp/src/main/java/com/ibm/fhir/bulkimport/ImportPartitionCollector.java
  fhir-bulkimportexport-webapp/src/main/java/com/ibm/fhir/bulkimport/ImportPartitionMapper.java
  fhir-bulkimportexport-webapp/src/main/java/com/ibm/fhir/bulktools/Main.java
  fhir-config/src/main/java/com/ibm/fhir/config/FHIRConfiguration.java
  fhir-config/src/test/resources/fhirConfig.json
  fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/client/BulkDataClient.java
  fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/util/BulkDataImportUtil.java
  fhir-operation-bulkdata/src/test/java/com/ibm/fhir/operation/bulkdata/client/BulkDataClientMain.java
  fhir-operation-bulkdata/src/test/resources/testdata/config/default/fhir-server-config.json
  fhir-server-test/src/test/java/com/ibm/fhir/server/test/ImportOperationTest.java
  fhir-server/liberty-config/config/default/fhir-server-config-db2.json
  fhir-server/liberty-config/config/default/fhir-server-config-postgresql.json
  fhir-server/liberty-config/config/default/fhir-server-config.json
  fhir-server/liberty-config/resources/security/kafka.client.keystore.jks
  fhir-server/liberty-config/resources/security/kafka.client.keystore.p12
  fhir-server/liberty-config/resources/security/kafka.client.truststore.jks
  fhir-server/liberty-config/resources/security/kafka.client.truststore.p12
Labels: bug

#985 BulkData $import API improvement - Exit Status #949
  docs/src/pages/guides/FHIRServerUsersGuide.md
  fhir-bulkimportexport-webapp/src/main/java/META-INF/batch-jobs/FhirBulkImportChunkJob.xml
  fhir-bulkimportexport-webapp/src/main/java/com/ibm/fhir/bulkcommon/BulkDataUtils.java
  fhir-bulkimportexport-webapp/src/main/java/com/ibm/fhir/bulkimport/ImportPartitionCollector.java
  fhir-bulkimportexport-webapp/src/main/java/com/ibm/fhir/bulkimport/ImportPartitionMapper.java
  fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/client/BulkDataClient.java
  fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/model/JobExecutionResponse.java
  fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/model/JobInstanceRequest.java
  fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/model/type/JobParameter.java
Labels: bulk-data, documentation, enhancement

#991 Documentation issue: Db2 - (transactional) does not exist in IBM Clo…
  docs/src/pages/guides/DB2OnCloudSetup.md
Labels: documentation

#987 fhir-persistence-schema - Update for additional property #986
  fhir-persistence-schema/README.md
Labels: documentation

#984 BulkData $bulkdata-status DELETE API must stop first #952
  fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/client/BulkDataClient.java
  fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/processor/impl/CosExportImpl.java
  fhir-server-test/src/test/java/com/ibm/fhir/server/test/ImportOperationTest.java
  fhir-server/src/main/java/com/ibm/fhir/server/resources/Operation.java
Labels: bulk-data

#973 Add NATS support for FHIR notifications
  README.md
  build/README-DB2.md
  build/docker/docker-compose.yml
  build/docker/nats/config-1.conf
  build/docker/nats/config-2.conf
  build/docker/nats/config-3.conf
  docs/src/pages/guides/FHIRServerUsersGuide.md
  fhir-config/src/main/java/com/ibm/fhir/config/FHIRConfiguration.java
  fhir-install/pom.xml
  fhir-notification-nats/.gitignore
  fhir-notification-nats/README.MD
  fhir-notification-nats/pom.xml
  fhir-notification-nats/src/main/java/com/ibm/fhir/notifications/nats/impl/FHIRNotificationNATSPublisher.java
  fhir-parent/pom.xml
  fhir-server-test/src/test/nodejs/.gitignore
  fhir-server-test/src/test/nodejs/nats-subscriber.js
  fhir-server-test/src/test/nodejs/package.json
  fhir-server/liberty-config/config/default/fhir-server-config-db2.json
  fhir-server/liberty-config/config/default/fhir-server-config.json
  fhir-server/pom.xml
  fhir-server/src/main/java/com/ibm/fhir/server/listener/FHIRServletContextListener.java
  fhir-server/src/main/java/com/ibm/fhir/server/resources/Capabilities.java
Labels: new-module
