Repository LinuxForHealth/FHIR, pull requests merged in 2020-03, with the labels that each got.

#756 e2e windows tests report success even when e2e tests fail #698
  build/tests.ps1
Labels: automation

#764 Issue 744
  fhir-persistence-schema/docs/DB2MultiTenancy.md
  fhir-persistence-schema/docs/permissions-overview.png
Labels: schema

#775 Issue 774 - fix javadoc automation and add link to site for the javadoc index
  .github/workflows/javadocs.yml
  docs/src/gatsby-theme-carbon/components/LeftNav/ResourceLinks.js
Labels: automation, documentation

#782 Document the schema migration process #270
  fhir-persistence-schema/docs/DB2SchemaMigration.md
  fhir-persistence-schema/docs/mt-table.png
Labels: schema, schema-change, search

#816 migration issue with embedded versions (hard coded in two spots)
  fhir-database-utils/src/main/java/com/ibm/fhir/database/utils/model/Table.java
  fhir-database-utils/src/main/java/com/ibm/fhir/database/utils/model/VersionedSchemaObject.java
Labels: schema, schema-change

#813 Prepopulate ResourceType Names in Tenant Allocation #811
  fhir-database-utils/src/main/java/com/ibm/fhir/database/utils/common/CommonDatabaseAdapter.java
  fhir-persistence-schema/src/main/java/com/ibm/fhir/schema/app/Main.java
  fhir-persistence-schema/src/main/java/com/ibm/fhir/schema/control/Db2PopulateResourceTypes.java
  fhir-persistence-schema/src/main/resources/resource_types.properties
  fhir-persistence-schema/src/test/java/com/ibm/fhir/schema/control/Db2PopulateResourceTypesTest.java
Labels: bug, schema, schema-change

#839 Add information about setting the tenantKey
  docs/src/pages/guides/FHIRServerUsersGuide.md
Labels: documentation

#842 Reduce the Default Pool Size for the Schema Generator #841
  fhir-persistence-schema/src/main/java/com/ibm/fhir/schema/app/Main.java
  fhir-persistence-schema/src/main/java/com/ibm/fhir/schema/control/FhirSchemaConstants.java
Labels: automation, schema

#848 Fix FHIRResourceType.ValueSet issue in docs
  fhir-persistence-schema/docs/DB2SchemaMigration.md
Labels: documentation

#847 --add-tenant-key missing in docs #846
  fhir-persistence-schema/README.md
Labels: documentation

#870 Update Readme.md with additional components
  README.md
Labels: documentation
