Repository LinuxForHealth/FHIR, pull requests merged in 2020-10, with the labels that each got.

#1524 Implicit base not picked up in FHIR Reference search #300
  docs/src/pages/Conformance.md
  fhir-bulkimportexport-webapp/src/main/java/META-INF/batch-jobs/FhirBulkExportChunkJob.xml
  fhir-bulkimportexport-webapp/src/main/java/META-INF/batch-jobs/FhirBulkExportGroupChunkJob.xml
  fhir-bulkimportexport-webapp/src/main/java/META-INF/batch-jobs/FhirBulkExportPatientChunkJob.xml
  fhir-bulkimportexport-webapp/src/main/java/com/ibm/fhir/jbatch/bulkdata/common/Constants.java
  fhir-bulkimportexport-webapp/src/main/java/com/ibm/fhir/jbatch/bulkdata/export/group/ChunkReader.java
  fhir-bulkimportexport-webapp/src/main/java/com/ibm/fhir/jbatch/bulkdata/export/patient/ChunkReader.java
  fhir-bulkimportexport-webapp/src/main/java/com/ibm/fhir/jbatch/bulkdata/export/system/ChunkReader.java
  fhir-config/src/main/java/com/ibm/fhir/config/FHIRRequestContext.java
  fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/JDBCQueryBuilder.java
  fhir-persistence-jdbc/src/test/java/com/ibm/fhir/persistence/jdbc/search/test/JDBCSearchReferenceTest.java
  fhir-persistence/src/test/java/com/ibm/fhir/persistence/search/test/AbstractSearchReferenceTest.java
  fhir-persistence/src/test/java/com/ibm/fhir/persistence/test/common/AbstractPersistenceTest.java
  fhir-persistence/src/test/resources/config/reference/extension-search-parameters.json
  fhir-search/src/main/java/com/ibm/fhir/search/parameters/QueryParameterValue.java
  fhir-search/src/main/java/com/ibm/fhir/search/reference/ReferenceParameterHandler.java
  fhir-search/src/main/java/com/ibm/fhir/search/reference/value/CanonicalUrlHandlerImpl.java
  fhir-search/src/main/java/com/ibm/fhir/search/reference/value/IdHandlerImpl.java
  fhir-search/src/main/java/com/ibm/fhir/search/reference/value/ParameterValueHandler.java
  fhir-search/src/main/java/com/ibm/fhir/search/reference/value/TypeIdHandlerImpl.java
  fhir-search/src/main/java/com/ibm/fhir/search/reference/value/UrlHandlerImpl.java
  fhir-search/src/main/java/com/ibm/fhir/search/uri/UriBuilder.java
  fhir-search/src/main/java/com/ibm/fhir/search/util/SearchUtil.java
  fhir-search/src/test/java/com/ibm/fhir/search/reference/ReferenceTypeTest.java
  fhir-search/src/test/java/com/ibm/fhir/search/sort/test/SortParameterParseTest.java
  fhir-search/src/test/java/com/ibm/fhir/search/sort/test/SortParameterTest.java
  fhir-search/src/test/java/com/ibm/fhir/search/test/BaseSearchTest.java
  fhir-server-test/src/test/java/com/ibm/fhir/server/test/SearchTest.java
  operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/client/BulkDataClient.java
  operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/config/BulkDataConfigUtil.java
  operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/model/JobExecutionResponse.java
  operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/model/JobInstanceRequest.java
  operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/model/type/JobParameter.java
  operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/processor/impl/CosExportImpl.java
Labels: ci-skip, search

#1533 doc: fhir operation framework
  docs/src/data/nav-items.yaml
  docs/src/pages/guides/FHIROperationFramework.md
Labels: documentation

#1558 fix: stored procedures are not updatable due to a missing boolean = true
  fhir-database-utils/src/main/java/com/ibm/fhir/database/utils/model/BaseObject.java
  fhir-persistence-schema/src/main/java/com/ibm/fhir/schema/app/Main.java
Labels: bug

#1556 issue #1315 - instantiates field represents the registered capabilities
  fhir-server-test/src/test/java/com/ibm/fhir/client/test/FHIRClientTest.java
  fhir-server/src/main/java/com/ibm/fhir/server/resources/Capabilities.java
  operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/BulkDataResourceProvider.java
  operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/util/IndexGenerator.java
  operation/fhir-operation-bulkdata/src/main/resources/META-INF/services/com.ibm.fhir.registry.spi.FHIRRegistryResourceProvider
  operation/fhir-operation-bulkdata/src/main/resources/OperationDefinition-group-export.json
  operation/fhir-operation-bulkdata/src/main/resources/OperationDefinition-patient-export.json
  operation/fhir-operation-bulkdata/src/main/resources/export.json
  operation/fhir-operation-bulkdata/src/main/resources/hl7/fhir/uv/bulkdata/package/.index.json
  operation/fhir-operation-bulkdata/src/main/resources/hl7/fhir/uv/bulkdata/package/CapabilityStatement-bulk-data.json
  operation/fhir-operation-bulkdata/src/main/resources/import.json
  operation/fhir-operation-bulkdata/src/main/resources/status.json
Labels: ci-skip

#1574 Documentation for BulkImport javabatch job #809
  docs/src/pages/guides/FHIRBulkOperations.md
Labels: documentation

#1580 add single smart capability to the default list
  fhir-server/liberty-config/config/default/fhir-server-config.json
Labels: ci-skip

#1585 fix: add missing igs to the maven profiles in the release process
  build/release/build.sh
Labels: automation

#1614 ci: wrong profile and dependency name
  build/release/build.sh
  fhir-validation/pom.xml
Labels: automation

#1617 fix: site unable to compile due to invalid export variable in a recent gatsby-remark-plugin update
  docs/package.json
Labels: documentation

#1618 Update feature request to include acceptance criteria
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: ci-skip

#1646 fix: website requires balanced xhtml
  docs/src/pages/performance/performance-450.md
Labels: documentation
