Repository LinuxForHealth/FHIR, pull requests merged in 2020-12, with the labels that each got.

#1770 Corrected the command flag for tenant name reuse step
  fhir-persistence-schema/docs/DropTenant.md
Labels: ci-skip

#1779 fix: postgres/db2 refresh of the stored procedure
  fhir-persistence-schema/src/main/java/com/ibm/fhir/schema/app/Main.java
Labels: bug

#1791 fix typo in examples
  fhir-persistence-schema/README.md
Labels: ci-skip

#1806 doc: compilation errors are now fixed
  docs/src/pages/MustGather.md
Labels: documentation

#1804 IBM FHIR Server audit does not log bundles correctly. #1803
  fhir-audit/src/main/java/com/ibm/fhir/audit/logging/impl/WhcAuditCadfLogService.java
  fhir-server/src/main/java/com/ibm/fhir/server/resources/Batch.java
  fhir-server/src/main/java/com/ibm/fhir/server/util/RestAuditLogger.java
Labels: cloud portability

#1810 doc: adding code of conduct md file to root of repository
  CODE_OF_CONDUCT.md
Labels: ci-skip, documentation

#1811 doc: update to clarify the experimental use of the ibm-fhir-schematool
  README.md
Labels: ci-skip, documentation

#1812 add communication method
  CODE_OF_CONDUCT.md
Labels: ci-skip

#1761 Enable OpenLiberty override the fhiropenapi functionality #1760
  fhir-server/liberty-config/configDropins/defaults/openapi.xml
  fhir-server/liberty-config/server.xml
Labels: cloud portability

#1820 fix: it tests were not running for drug formulary and c4bb
  fhir-server-test/src/test/java/com/ibm/fhir/server/test/profiles/CarinBlueButtonTest.java
  fhir-server-test/src/test/java/com/ibm/fhir/server/test/profiles/DavinciDrugFormularyTest.java
Labels: bug

#1826 Code Review for FHIR Audit
  docs/src/pages/guides/FHIRServerUsersGuide.md
  fhir-audit/src/main/java/com/ibm/fhir/audit/cadf/CadfEvent.java
  fhir-audit/src/main/java/com/ibm/fhir/audit/cadf/CadfResource.java
  fhir-audit/src/test/java/com/ibm/fhir/audit/cadf/test/CadfModelTest.java
Labels: bug

#1827 Removed auditLogService <extension url="http://ibm.com/fhir/extension/auditLogProperties">
  fhir-server/src/main/java/com/ibm/fhir/server/resources/Capabilities.java
Labels: security

#1829 fix: referenced license was incorrect
  fhir-install/Dockerfile
  fhir-install/licenses/LICENSE
  fhir-install/pom.xml
Labels: bug

#1832 Package name consistency issue after Code Review of FHIR-Audit Config
  fhir-server/liberty-config/config/default/fhir-server-config-audit-config.json
  fhir-server/liberty-config/config/default/fhir-server-config-audit-environment.json
Labels: ci-skip
