Repository LinuxForHealth/FHIR, pull requests merged in 2020-09, with the labels that each got.

#1464 README for fhir-persistence-schema: document pitfalls more explicitly…
  fhir-persistence-schema/README.md
Labels: ci-skip

#1475 Cleanup Docs
  fhir-persistence-schema/README.md
Labels: ci-skip, documentation

#1483 Update Project Readme.md with two new projects - fhir-bucket and fhi…
  README.md
Labels: ci-skip

#1497 valueUrl is used incorrectly in the CapabilityStatement #1496
  fhir-server/src/main/java/com/ibm/fhir/server/resources/Capabilities.java
Labels: connectathon

#1501 US-Core: Create Integration Tests for STU3 Release 3.1.1 #1311
  fhir-examples/src/main/resources/json/profiles/fhir-ig-us-core/Bundle-66c8856b-ba11-4876-8aa8-467aad8c11a2.json
  fhir-server-test/src/test/java/com/ibm/fhir/server/test/profiles/ProfilesTestBase.java
  fhir-server-test/src/test/java/com/ibm/fhir/server/test/profiles/USCoreAllergyIntoleranceTest.java
  fhir-server-test/src/test/java/com/ibm/fhir/server/test/profiles/USCoreDiagnosticReportLabTest.java
  fhir-server-test/src/test/java/com/ibm/fhir/server/test/profiles/USCoreDiagnosticReportNoteTest.java
  fhir-server-test/src/test/java/com/ibm/fhir/server/test/profiles/USCoreDocumentReferenceTest.java
  fhir-server-test/src/test/java/com/ibm/fhir/server/test/profiles/USCoreEncounterTest.java
  fhir-server-test/src/test/java/com/ibm/fhir/server/test/profiles/USCoreGoalTest.java
  fhir-server-test/src/test/java/com/ibm/fhir/server/test/profiles/USCoreImmunizationTest.java
  fhir-server-test/src/test/java/com/ibm/fhir/server/test/profiles/USCoreImplantableDeviceTest.java
  fhir-server-test/src/test/java/com/ibm/fhir/server/test/profiles/USCoreLocationTest.java
  fhir-server-test/src/test/java/com/ibm/fhir/server/test/profiles/USCoreMedicationRequestTest.java
  fhir-server-test/src/test/java/com/ibm/fhir/server/test/profiles/USCoreMedicationTest.java
  fhir-server-test/src/test/java/com/ibm/fhir/server/test/profiles/USCoreObservationLabTest.java
  fhir-server-test/src/test/java/com/ibm/fhir/server/test/profiles/USCoreObservationPediatricBMIForAgeTest.java
  fhir-server-test/src/test/java/com/ibm/fhir/server/test/profiles/USCoreObservationPediatricHeadOccipitalFrontalCircumferencePercentileTest.java
  fhir-server-test/src/test/java/com/ibm/fhir/server/test/profiles/USCoreObservationPediatricWeightForHeightTest.java
  fhir-server-test/src/test/java/com/ibm/fhir/server/test/profiles/USCoreObservationPulseOximetryTest.java
  fhir-server-test/src/test/java/com/ibm/fhir/server/test/profiles/USCoreObservationSmokingStatusTest.java
  fhir-server-test/src/test/java/com/ibm/fhir/server/test/profiles/USCoreOrganizationTest.java
  fhir-server-test/src/test/java/com/ibm/fhir/server/test/profiles/USCorePatientTest.java
  fhir-server-test/src/test/java/com/ibm/fhir/server/test/profiles/USCorePractitionerAndPractitionerRoleTest.java
  fhir-server-test/src/test/java/com/ibm/fhir/server/test/profiles/USCoreProcedureTest.java
Labels: cms-interop, connectathon

#1528 doc: changed two links to the new locations
  docs/src/pages/Conformance.md
Labels: documentation
