Repository LinuxForHealth/FHIR, pull requests merged in 2020-07, with the labels that each got.

#1335 Issue #1327 Improve execution plans for search
  fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/InclusionQuerySegmentAggregator.java
  fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/JDBCQueryBuilder.java
  fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/QuerySegmentAggregator.java
  fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/type/LocationParmBehaviorUtil.java
  fhir-persistence-jdbc/src/test/java/com/ibm/fhir/persistence/jdbc/test/util/LocationParmBehaviorUtilTest.java
  fhir-persistence/src/main/java/com/ibm/fhir/persistence/util/AbstractQueryBuilder.java
Labels: performance

#1343 README Update from Customer Feedback
  fhir-persistence-schema/README.md
Labels: ci-skip, documentation

#1348 Fix for PostgresTranslator to Support Advanced Connections Properties
  fhir-database-utils/src/main/java/com/ibm/fhir/database/utils/postgresql/PostgreSqlTranslator.java
  fhir-persistence-schema/README.md
Labels: bug

#1349 Increase Poolsize to speed up automation
  .github/workflows/build.yml
  build/docker/updateSchema.sh
  fhir-persistence-schema/README.md
Labels: automation

#1359 Clarify what "API-stable" means
  README.md
Labels: ci-skip

#1364 issue 1362 Use timestamp prefix for identity strings to reduce random reads during ingestion
  fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/impl/FHIRPersistenceJDBCImpl.java
  fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/LogicalIdentityProvider.java
  fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/TimestampPrefixedUUID.java
  fhir-persistence-jdbc/src/test/java/com/ibm/fhir/persistence/jdbc/test/util/TimestampPrefixedUUIDTest.java
Labels: performance

#1357 Clarify support for http and https and cleanup logged error
  docs/src/pages/guides/FHIRBulkOperations.md
  fhir-bulkimportexport-webapp/src/main/java/com/ibm/fhir/jbatch/bulkdata/common/BulkDataUtils.java
Labels: bug, documentation

#1342 Update to new version of jcip
  fhir-model/pom.xml
  fhir-parent/pom.xml
  fhir-path/pom.xml
Labels: automation
