Repository LinuxForHealth/FHIR, pull requests merged in 2021-07, with the labels that each got.

#2571 fix the flag name for client-driven reindex
  fhir-bucket/README.md
Labels: ci-skip

#2587 Issue #2582 - add support for fail-fast validation
  docs/src/pages/guides/FHIRServerUsersGuide.md
  fhir-config/src/main/java/com/ibm/fhir/config/FHIRConfiguration.java
  fhir-path/src/main/java/com/ibm/fhir/path/util/DiagnosticsEvaluationListener.java
  fhir-server/src/main/java/com/ibm/fhir/server/util/FHIRRestHelper.java
  fhir-validation/src/main/java/com/ibm/fhir/validation/FHIRValidator.java
  fhir-validation/src/main/java/com/ibm/fhir/validation/util/FHIRValidationUtil.java
  fhir-validation/src/test/java/com/ibm/fhir/validation/test/FailFastValidationTest.java
Labels: configuration

#2595 Issue #2583 - update copyright header
  fhir-model/src/main/java/com/ibm/fhir/model/annotation/Constraint.java
Labels: ci-skip

#2623 Issue #2583 - update constraint factory toString method
  fhir-model/src/main/java/com/ibm/fhir/model/constraint/factory/ConstraintFactory.java
Labels: ci-skip

#2633 Issue #2583 - comments / whitespace only
  fhir-model/src/main/java/com/ibm/fhir/model/constraint/spi/ConstraintProvider.java
  fhir-model/src/main/java/com/ibm/fhir/model/constraint/spi/ConstraintValidator.java
Labels: ci-skip

#2636 Update for Postgres vacuum settings
  fhir-database-utils/src/main/java/com/ibm/fhir/database/utils/postgres/PostgresVacuumSettingDAO.java
  fhir-persistence-schema/src/main/java/com/ibm/fhir/schema/control/FhirResourceTableGroup.java
  fhir-persistence-schema/src/main/java/com/ibm/fhir/schema/control/FhirSchemaGenerator.java
  fhir-persistence-schema/src/main/java/com/ibm/fhir/schema/control/FhirSchemaVersion.java
  fhir-server-test/src/test/java/com/ibm/fhir/server/test/SearchRevIncludeTest.java
Labels: postgres

#2637 Javadoc-only update
  fhir-cache/src/main/java/com/ibm/fhir/cache/CacheKey.java
Labels: ci-skip

#2638 Doc only change
  fhir-path/src/main/java/com/ibm/fhir/path/evaluator/FHIRPathEvaluator.java
Labels: ci-skip

#2647 Update the TableName for Vacuum during update-schema
  fhir-database-utils/src/main/java/com/ibm/fhir/database/utils/postgres/PostgresVacuumSettingDAO.java
  fhir-persistence-schema/src/main/java/com/ibm/fhir/schema/control/FhirResourceTableGroup.java
Labels: persistence

#2646 Fail to process _typeFilter #2645
  fhir-bulkdata-webapp/src/main/java/com/ibm/fhir/bulkdata/common/BulkDataUtils.java
  fhir-server-test/src/test/java/com/ibm/fhir/server/test/bulkdata/ExportOperationTest.java
  fhir-server/src/main/java/com/ibm/fhir/server/util/FHIRUrlParser.java
Labels: bulk-data
