Repository LinuxForHealth/FHIR, pull requests merged in 2021-09, with the labels that each got.

#2727 BulkData: Delete Job #2713
  fhir-server-test/src/test/java/com/ibm/fhir/server/test/bulkdata/ExportOperationTest.java
  operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/client/BulkDataClient.java
  operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/client/action/BulkDataClientAction.java
  operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/client/action/batch/BatchCancelRequestAction.java
  operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/model/JobExecutionResponse.java
  operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/model/JobInstanceResponse.java
Labels: bulk-data, ci-skip

#2740 Update for the fhir-bulkdata-webapp
  fhir-bulkdata-webapp/src/main/java/com/ibm/fhir/bulkdata/jbatch/export/fast/ExportPartitionAnalyzer.java
  fhir-bulkdata-webapp/src/main/java/com/ibm/fhir/bulkdata/jbatch/export/system/ExportPartitionAnalyzer.java
  fhir-bulkdata-webapp/src/main/java/com/ibm/fhir/bulkdata/jbatch/listener/StepChunkListener.java
Labels: bulk-data

#2760 Update Javadoc Support #2750
  .github/workflows/javadocs.yml
Labels: automation

#2771 Delete .travis.yml
  .travis.yml
Labels: automation

#2775 fhir-persistence-schema CLI drop schema gives an error #2758
  build/docker/minio/Dockerfile
  fhir-persistence-schema/src/main/java/com/ibm/fhir/schema/app/Main.java
  fhir-persistence-schema/src/main/java/com/ibm/fhir/schema/control/FhirResourceTableGroup.java
  fhir-persistence-schema/src/main/java/com/ibm/fhir/schema/control/FhirSchemaGenerator.java
  fhir-persistence-schema/src/main/java/com/ibm/fhir/schema/control/JavaBatchSchemaGenerator.java
  fhir-persistence-schema/src/main/java/com/ibm/fhir/schema/control/OAuthSchemaGenerator.java
  fhir-persistence-schema/src/test/java/com/ibm/fhir/schema/app/DataSchemaGeneratorTest.java
  fhir-persistence-schema/src/test/java/com/ibm/fhir/schema/app/JavaBatchSchemaGeneratorTest.java
  fhir-persistence-schema/src/test/java/com/ibm/fhir/schema/app/OAuthSchemaGeneratorTest.java
Labels: schema

#2792 Potential race condition when create overlaps with erase (hard-delete) #2454
  fhir-server-test/src/test/java/com/ibm/fhir/server/test/ConcurrentEraseUpdateTest.java
  fhir-server-test/src/test/java/com/ibm/fhir/server/test/concurrent/InteractionFactory.java
  fhir-server-test/src/test/java/com/ibm/fhir/server/test/operation/EraseOperationTest.java
Labels: ci-skip

#2796 cicd: Update Dockerfile with note and revert to latest
  build/docker/minio/Dockerfile
Labels: automation

#2817 Update Loggers to use the proper classes
  fhir-bucket/src/main/java/com/ibm/fhir/bucket/persistence/AddResourceBundleErrors.java
  fhir-bucket/src/main/java/com/ibm/fhir/bucket/persistence/GetResourceRefsForBundleLine.java
  fhir-bucket/src/main/java/com/ibm/fhir/bucket/persistence/MergeResourceTypes.java
  fhir-bucket/src/main/java/com/ibm/fhir/bucket/persistence/MergeResources.java
  fhir-bucket/src/main/java/com/ibm/fhir/bucket/persistence/ResourceTypesReader.java
  fhir-bucket/src/main/java/com/ibm/fhir/bucket/reindex/ServerDrivenReindexOperation.java
Labels: technical debt
