Repository LinuxForHealth/FHIR, pull requests merged in 2021-03, with the labels that each got.

#2003 issue 1955 use resource subset for all operations in schema tool
  fhir-database-utils/src/main/java/com/ibm/fhir/database/utils/common/ReorgTable.java
  fhir-database-utils/src/main/java/com/ibm/fhir/database/utils/model/CharColumn.java
  fhir-database-utils/src/main/java/com/ibm/fhir/database/utils/model/Table.java
  fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/dao/impl/FetchResourceChangesDAO.java
  fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/dao/impl/ResourceTokenValueRec.java
  fhir-persistence-schema/src/main/java/com/ibm/fhir/schema/app/Main.java
  fhir-persistence-schema/src/main/java/com/ibm/fhir/schema/control/BackfillResourceChangeLogDb2.java
Labels: ci-skip

#2005 issue-1993 use better default value for PostgreSQL query tuning options
  docs/src/pages/guides/FHIRServerUsersGuide.md
  fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/postgresql/SetPostgresOptimizerOptions.java
  fhir-server/liberty-config/config/default/fhir-server-config-postgresql.json
  fhir-server/liberty-config/config/default/fhir-server-config.json
Labels: performance

#2009 Windows docker build of fhir server fails non-zero code: 127 #2007
  .gitattributes
Labels: automation

#2013 issue 1683 and issue 2011 fixed migration for Postgres and added last…
  fhir-database-utils/src/main/java/com/ibm/fhir/database/utils/common/DropPrimaryKey.java
  fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/derby/DerbyResourceDAO.java
  fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/postgres/PostgresResourceNoProcDAO.java
  fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/util/JDBCQueryBuilder.java
  fhir-persistence-schema/src/main/java/com/ibm/fhir/schema/control/FhirResourceTableGroup.java
  fhir-persistence-schema/src/main/java/com/ibm/fhir/schema/control/FhirSchemaVersion.java
  fhir-persistence-schema/src/main/java/com/ibm/fhir/schema/control/InitializeLogicalIdIsDeleted.java
  fhir-persistence-schema/src/main/resources/db2/add_any_resource.sql
  fhir-persistence-schema/src/main/resources/postgres/add_any_resource.sql
  fhir-server/src/main/java/com/ibm/fhir/server/listener/FHIRServletContextListener.java
Labels: bug, schema-change

#2010 share derby-bootstrap script for bootstrapping derby dbs
  build/derby-bootstrap.sh
Labels: ci-skip

#2020 issue 1958 correlated update not supported in Derby so use JDBC batch…
  fhir-database-utils/src/main/java/com/ibm/fhir/database/utils/version/SchemaConstants.java
  fhir-persistence-schema/src/main/java/com/ibm/fhir/schema/control/InitializeLogicalIdIsDeleted.java
  fhir-server/src/main/java/com/ibm/fhir/server/util/FHIRRestHelper.java
Labels: schema-change

#2028 Add Import CI
  build/docker/copy-server-config.sh
  fhir-server-test/src/test/java/com/ibm/fhir/server/test/bulkdata/ImportOperationTest.java
  operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/config/preflight/impl/FilePreflight.java
  operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/config/preflight/impl/HttpsPreflight.java
  operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/config/preflight/impl/S3Preflight.java
Labels: bulk-data

#2038 issue 2035 define and use sharedLibDerby, sharedLibDb2 and sharedLibP…
  docs/src/pages/guides/DB2OnCloudSetup.md
  docs/src/pages/guides/FHIRPerformanceGuide.md
  docs/src/pages/guides/FHIRServerUsersGuide.md
  fhir-server/liberty-config/configDropins/defaults/datasource.xml
  fhir-server/liberty-config/configDropins/disabled/cloud.xml
  fhir-server/liberty-config/configDropins/disabled/datasource-db2.xml
  fhir-server/liberty-config/configDropins/disabled/datasource-derby.xml
  fhir-server/liberty-config/configDropins/disabled/datasource-postgresql.xml
  fhir-server/liberty-config/configDropins/disabled/db2-cloud/bulkdata.xml
  fhir-server/liberty-config/configDropins/disabled/db2/bulkdata.xml
  fhir-server/liberty-config/configDropins/disabled/oidcProvider.xml
  fhir-server/liberty-config/configDropins/disabled/postgres/bulkdata.xml
  fhir-server/liberty-config/server.xml
Labels: P1

#2030 issue 2029 - check PK constraint and ROW_ID exist before attempting t…
  docs/src/pages/Conformance.md
  fhir-database-utils/src/main/java/com/ibm/fhir/database/utils/common/CreateIndexStatement.java
  fhir-database-utils/src/main/java/com/ibm/fhir/database/utils/common/DropColumn.java
  fhir-database-utils/src/main/java/com/ibm/fhir/database/utils/common/DropPrimaryKey.java
  fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/dao/impl/FetchResourceChangesDAO.java
  fhir-persistence-schema/src/main/java/com/ibm/fhir/schema/app/Main.java
  fhir-persistence-schema/src/main/java/com/ibm/fhir/schema/control/FhirResourceTableGroup.java
  fhir-persistence-schema/src/main/java/com/ibm/fhir/schema/control/FhirSchemaGenerator.java
  fhir-persistence/src/main/java/com/ibm/fhir/persistence/util/FHIRPersistenceUtil.java
  fhir-server/src/main/java/com/ibm/fhir/server/util/FHIRRestHelper.java
Labels: P1, bug

#2052 Update to the bulkdata documentation
  README.md
  docs/src/pages/guides/FHIRBulkOperations.md
  docs/src/pages/guides/FHIRServerUsersGuide.md
Labels: ci-skip, documentation

#2056 reformat the acceptance criteria a tad
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: ci-skip

#2061 Improve Error Handling with POST to $import
  operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/ImportOperation.java
Labels: bulk-data

#2078 Fix: Reporter didn't aggregate the total
  fhir-bulkdata-webapp/src/main/java/com/ibm/fhir/bulkdata/jbatch/load/listener/Reporter.java
Labels: bulk-data

#2074 Audit log entry for bulk data export should have a resource type
  fhir-audit/src/main/java/com/ibm/fhir/audit/beans/Context.java
  fhir-audit/src/main/java/com/ibm/fhir/audit/beans/FHIRContext.java
  fhir-bulkdata-webapp/src/main/java/com/ibm/fhir/bulkdata/audit/BulkAuditLogger.java
  fhir-bulkdata-webapp/src/main/java/com/ibm/fhir/bulkdata/export/group/resource/GroupHandler.java
  fhir-bulkdata-webapp/src/main/java/com/ibm/fhir/bulkdata/export/patient/resource/PatientResourceHandler.java
  fhir-bulkdata-webapp/src/main/java/com/ibm/fhir/bulkdata/jbatch/export/fast/ResourcePayloadReader.java
  fhir-bulkdata-webapp/src/main/java/com/ibm/fhir/bulkdata/jbatch/export/patient/ChunkReader.java
  fhir-bulkdata-webapp/src/main/java/com/ibm/fhir/bulkdata/jbatch/export/system/ChunkReader.java
  fhir-bulkdata-webapp/src/main/java/com/ibm/fhir/bulkdata/jbatch/load/ChunkWriter.java
Labels: bulk-data

#1991 Issue 1044 - Implementation of the $everything operation
  README.md
  docs/src/pages/Conformance.md
  fhir-install/pom.xml
  fhir-model/src/main/java/com/ibm/fhir/model/util/ModelSupport.java
  fhir-parent/pom.xml
  fhir-search/src/main/java/com/ibm/fhir/search/SearchConstants.java
  fhir-server-test/src/test/java/com/ibm/fhir/server/test/BundleTest.java
  fhir-server-test/src/test/java/com/ibm/fhir/server/test/FHIRPatchTest.java
  fhir-server-test/src/test/java/com/ibm/fhir/server/test/FHIRServerTestBase.java
  fhir-server-test/src/test/java/com/ibm/fhir/server/test/everything/EverythingOperationTest.java
  fhir-server-test/src/test/resources/testdata/everything-operation/Antonia30_Acosta403.json
  fhir-server-webapp/pom.xml
  fhir-server/src/main/java/com/ibm/fhir/server/util/FHIRRestHelper.java
  operation/fhir-operation-everything/pom.xml
  operation/fhir-operation-everything/src/main/java/com/ibm/fhir/operation/everything/EverythingOperation.java
  operation/fhir-operation-everything/src/main/resources/META-INF/services/com.ibm.fhir.server.operation.spi.FHIROperation
  operation/fhir-operation-everything/src/main/resources/everything.json
  operation/fhir-operation-everything/src/test/java/com/ibm/fhir/operation/everything/EverythingOperationTest.java
  operation/fhir-operation-everything/src/test/resources/parameters-end.json
  operation/fhir-operation-everything/src/test/resources/parameters-start-end-count-since.json
  operation/fhir-operation-everything/src/test/resources/parameters-start-end-count.json
  operation/fhir-operation-everything/src/test/resources/parameters-start-end.json
  operation/fhir-operation-everything/src/test/resources/parameters-start.json
  operation/fhir-operation-everything/src/test/resources/parameters-type.json
Labels: new-module

#2069 Issue 2063: avoid exporting abstract resource types
  fhir-server-test/src/test/java/com/ibm/fhir/server/test/bulkdata/ExportOperationTest.java
  operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/ExportOperation.java
  operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/util/BulkDataExportUtil.java
Labels: bulk-data

#2060 Patient Export Results in duplicate data included in the Write #2058
  fhir-bulkdata-webapp/src/main/java/com/ibm/fhir/bulkdata/dto/ReadResultDTO.java
  fhir-bulkdata-webapp/src/main/java/com/ibm/fhir/bulkdata/export/patient/resource/PatientResourceHandler.java
  fhir-bulkdata-webapp/src/main/java/com/ibm/fhir/bulkdata/jbatch/export/group/ChunkReader.java
  fhir-bulkdata-webapp/src/main/java/com/ibm/fhir/bulkdata/jbatch/export/patient/ChunkReader.java
  fhir-server-test/src/test/java/com/ibm/fhir/server/test/bulkdata/ExportOperationTest.java
Labels: bulk-data

#2115 Reindex fix for db2 mutlitenancy #2108
  fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/dao/ReindexResourceDAO.java
  fhir-server-test/src/test/java/com/ibm/fhir/server/test/operation/ReindexOperationTest.java
  fhir-server-test/src/test/java/testng.xml
Labels: persistence

#2127 Output missing when an bad incoming url is sent
  operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/client/BulkDataClient.java
Labels: bulk-data

#2129 Call into $bulkdata-status passing in the encoded job number
  docs/src/pages/guides/FHIRServerUsersGuide.md
  operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/StatusOperation.java
  operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/client/BulkDataClient.java
  operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/config/impl/AbstractSystemConfigurationImpl.java
  operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/model/transformer/JobIdEncodingTransformer.java
  operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/util/BulkDataExportUtil.java
  operation/fhir-operation-bulkdata/src/test/java/com/ibm/fhir/operation/bulkdata/model/transformer/JobIdEncodingTransformerTest.java
Labels: bulk-data

#2132 Integration Tests for Everything Operation don't run. #2131
  fhir-server-test/src/test/java/com/ibm/fhir/server/test/everything/EverythingOperationTest.java
  fhir-server-test/src/test/java/testng.xml
  fhir-server-webapp/pom.xml
  fhir-term-graph/pom.xml
  operation/fhir-operation-everything/src/main/java/com/ibm/fhir/operation/everything/EverythingOperation.java
Labels: testing

#2130 FHIRPath CLI #1283
  docs/src/pages/guides/FHIRValidationGuide.md
  fhir-path/pom.xml
  fhir-path/src/main/java/com/ibm/fhir/path/tools/Main.java
  fhir-path/src/test/java/com/ibm/fhir/path/tools/MainTest.java
Labels: enhancement

#2157 Add javadoc and convenience methods for Base64Binary #1186
  fhir-model/src/main/java/com/ibm/fhir/model/type/Base64Binary.java
  fhir-model/src/test/java/com/ibm/fhir/model/test/Base64BinaryTest.java
  fhir-tools/src/main/java/com/ibm/fhir/tools/CodeGenerator.java
Labels: bug

#2171 configure the maxChunkReadTime for Fast Export and configurable timeout for presigned URL #2150
  docs/src/pages/guides/FHIRServerUsersGuide.md
  fhir-bulkdata-webapp/src/main/java/com/ibm/fhir/bulkdata/jbatch/export/fast/ResourcePayloadReader.java
  fhir-server/liberty-config/config/default/fhir-server-config.json
  operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/config/ConfigurationAdapter.java
  operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/config/impl/AbstractSystemConfigurationImpl.java
  operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/model/url/DownloadUrl.java
Labels: bulk-data

#2183 Avoid the useless warning for jaxb-core,jaxb-api not found
  fhir-bulkdata-webapp/pom.xml
  fhir-parent/pom.xml
Labels: bug
