Repository LinuxForHealth/FHIR, pull requests merged in 2021-12, with the labels that each got.

#3041 bump spark-sql version to 3.2.0
  fhir-parent/pom.xml
Labels: dependencies

#3094 Update Test to use the specific version
  conformance/fhir-ig-carin-bb/src/test/java/com/ibm/fhir/ig/carin/bb/test/v100/ProviderTest.java
  conformance/fhir-ig-carin-bb/src/test/java/com/ibm/fhir/ig/carin/bb/test/v110/ProviderTest.java
  conformance/fhir-ig-us-core/src/test/java/com/ibm/fhir/ig/us/core/test/v311/ProviderTest.java
  conformance/fhir-ig-us-core/src/test/java/com/ibm/fhir/ig/us/core/test/v400/ProviderTest.java
Labels: ci-skip

#3100 Testcase issue need to set limit to page size #3099
  fhir-server-test/src/test/java/com/ibm/fhir/server/test/SearchAllTest.java
Labels: testing

#3110 Update MAINTAINERS.md
  MAINTAINERS.md
Labels: ci-skip

#3093 Bug fixes for CQL-related functions
  cql/fhir-cql/src/main/java/com/ibm/fhir/cql/engine/retrieve/SearchParameterFHIRRetrieveProvider.java
  cql/fhir-cql/src/main/java/com/ibm/fhir/cql/engine/searchparam/SearchParameterResolver.java
  cql/operation/fhir-operation-cpg/pom.xml
  cql/operation/fhir-operation-cpg/src/main/java/com/ibm/fhir/operation/cpg/AbstractCqlOperation.java
  cql/operation/fhir-operation-cpg/src/main/java/com/ibm/fhir/operation/cpg/CqlOperation.java
  cql/operation/fhir-operation-cpg/src/main/java/com/ibm/fhir/operation/cpg/LibraryEvaluateOperation.java
  cql/operation/fhir-operation-cpg/src/test/java/com/ibm/fhir/operation/cpg/CqlOperationTest.java
  cql/operation/fhir-operation-cpg/src/test/java/com/ibm/fhir/operation/cpg/LibraryEvaluateOperationTest.java
  cql/operation/fhir-operation-cqf/src/main/java/com/ibm/fhir/operation/cqf/AbstractMeasureOperation.java
  cql/operation/fhir-operation-cqf/src/main/java/com/ibm/fhir/operation/cqf/EvaluateMeasureOperation.java
  cql/operation/fhir-operation-cqf/src/main/java/com/ibm/fhir/operation/cqf/MeasureSubmitDataOperation.java
  cql/operation/fhir-operation-cqf/src/test/java/com/ibm/fhir/operation/cqf/EvaluateMeasureOperationTest.java
  cql/operation/fhir-operation-cqf/src/test/java/com/ibm/fhir/operation/cqf/MeasureSubmitDataOperationTest.java
  fhir-server-test/src/test/java/com/ibm/fhir/server/test/cpg/ServerCqlOperationTest.java
  fhir-server-test/src/test/java/com/ibm/fhir/server/test/cqf/BaseMeasureOperationTest.java
  fhir-server-test/src/test/java/com/ibm/fhir/server/test/cqf/ServerMeasureSubmitDataOperationTest.java
  fhir-server-test/src/test/resources/testdata/Bundle-ValueSets.json
  fhir-server-test/src/test/resources/testdata/MeasureReport-EXM104.json
Labels: cql

#3115 update convention template to avoid string that looks like xml element
  CONTRIBUTING.md
Labels: ci-skip

#3119 Error Message for Bad StorageProvider Configuration is unintentionally opaque #3118
  operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/ExportOperation.java
  operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/ImportOperation.java
  operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/OperationConstants.java
  operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/StatusOperation.java
  operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/config/preflight/impl/AzurePreflight.java
  operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/config/preflight/impl/FilePreflight.java
  operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/config/preflight/impl/HttpsPreflight.java
  operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/config/preflight/impl/NopPreflight.java
  operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/config/preflight/impl/S3Preflight.java
  operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/util/BulkDataImportUtil.java
  operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/util/CommonUtil.java
Labels: bulk-data

#3101 C4BB-ExplanationOfBenefit warning received - constraint not generated #3096
  conformance/fhir-ig-carin-bb/CHANGELOG
  conformance/fhir-ig-carin-bb/src/main/resources/hl7/fhir/us/carin-bb/110/package/StructureDefinition-C4BB-ExplanationOfBenefit.json
  conformance/fhir-ig-carin-bb/src/test/java/com/ibm/fhir/ig/carin/bb/test/v110/ProviderTest.java
Labels: ci-skip

#3128 Issue #2972 type filter on system history plus new resource history interaction
  docs/src/pages/Conformance.md
  fhir-config/src/main/java/com/ibm/fhir/config/FHIRRequestContext.java
  fhir-config/src/main/java/com/ibm/fhir/config/SystemConfigHelper.java
  fhir-config/src/test/java/com/ibm/fhir/config/test/SystemConfigHelperTest.java
  fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/dao/impl/FetchResourceChangesDAO.java
  fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/impl/FHIRPersistenceJDBCImpl.java
  fhir-persistence/src/main/java/com/ibm/fhir/persistence/FHIRPersistence.java
  fhir-persistence/src/main/java/com/ibm/fhir/persistence/HistorySortOrder.java
  fhir-persistence/src/main/java/com/ibm/fhir/persistence/context/FHIRSystemHistoryContext.java
  fhir-persistence/src/main/java/com/ibm/fhir/persistence/context/impl/FHIRSystemHistoryContextImpl.java
  fhir-persistence/src/main/java/com/ibm/fhir/persistence/util/FHIRPersistenceUtil.java
  fhir-persistence/src/test/java/com/ibm/fhir/persistence/test/MockPersistenceImpl.java
  fhir-server-spi/src/main/java/com/ibm/fhir/server/spi/operation/FHIRResourceHelpers.java
  fhir-server-test/src/test/java/com/ibm/fhir/server/test/SystemHistoryTest.java
  fhir-server/src/main/java/com/ibm/fhir/server/filter/rest/FHIRRestServletFilter.java
  fhir-server/src/main/java/com/ibm/fhir/server/resources/History.java
  fhir-server/src/main/java/com/ibm/fhir/server/util/FHIRRestHelper.java
  fhir-server/src/test/java/com/ibm/fhir/server/test/MockPersistenceImpl.java
  fhir-server/src/test/java/com/ibm/fhir/server/test/ServerResolveFunctionTest.java
  fhir-smart/src/test/java/com/ibm/fhir/smart/test/MockPersistenceImpl.java
  operation/fhir-operation-erase/src/test/java/com/ibm/fhir/operation/erase/mock/MockFHIRResourceHelpers.java
  operation/fhir-operation-member-match/src/test/java/com/ibm/fhir/operation/davinci/hrex/test/MemberMatchTest.java
Labels: breaking-change-java, break-change-api
