Repository LinuxForHealth/FHIR, pull requests merged in 2021-11, with the labels that each got.

#2931 DataStax Cassandra - incompatibility between 3.9.x and 4.1.3 in the FHIR Term Graph. #2930
  fhir-install/src/main/docker/ibm-fhir-schematool/Dockerfile
  fhir-install/src/main/docker/ibm-fhir-term-graph-loader/Dockerfile
  fhir-install/src/main/docker/ibm-fhir-term-graph-loader/run.sh
  term/fhir-term-graph-loader/pom.xml
  term/fhir-term-graph-loader/src/main/java/com/ibm/fhir/term/graph/loader/util/ConfigLoader.java
  term/fhir-term-graph/src/test/kubernetes/umlsTermGraphLoader.yml
Labels: bug

#2929 Issue 2843 - store both versioned and unversioned canonicals in ParametersMap
  fhir-parent/pom.xml
  fhir-search/pom.xml
  fhir-search/src/main/java/com/ibm/fhir/search/parameters/ParametersMap.java
  fhir-search/src/main/java/com/ibm/fhir/search/util/SearchUtil.java
  fhir-search/src/test/java/com/ibm/fhir/search/parameters/MultiTenantSearchParameterTest.java
  fhir-search/src/test/java/com/ibm/fhir/search/parameters/ParametersMapTest.java
  fhir-search/src/test/java/com/ibm/fhir/search/parameters/ParametersSearchUtilTest.java
  fhir-search/src/test/java/com/ibm/fhir/search/parameters/ParametersUtilTest.java
  fhir-search/src/test/java/com/ibm/fhir/search/test/ExtractParameterValuesTest.java
  fhir-search/src/test/resources/config/tenant4/fhir-server-config.json
  fhir-search/src/test/resources/config/tenant5/fhir-server-config.json
Labels: breaking-change-java

#2949 Audit record for PUTs should not always use "Update" #2471
  fhir-server/src/main/java/com/ibm/fhir/server/util/RestAuditLogger.java
Labels: audit

#2948 Avoid creating unnecessary tables for Resource and DomainResource resource types #713
  build/audit/kafka/docker-compose.yml
  build/derby-bootstrap.sh
  build/docker/docker-compose.yml
  build/migration/db2/4_current-migrate.sh
  build/migration/postgres/4_current-migrate.sh
  build/notifications/kafka/docker-compose.yml
  build/persistence/postgres/docker-compose.yml
  build/pre-integration-test.ps1
  build/pre-integration-test.sh
  fhir-database-utils/src/main/java/com/ibm/fhir/database/utils/db2/Db2CatalogAccess.java
  fhir-database-utils/src/main/java/com/ibm/fhir/database/utils/derby/DerbyAdapter.java
  fhir-persistence-schema/README.md
  fhir-persistence-schema/src/main/java/com/ibm/fhir/schema/app/Main.java
  fhir-persistence-schema/src/main/java/com/ibm/fhir/schema/control/FhirSchemaGenerator.java
  fhir-persistence-schema/src/main/java/com/ibm/fhir/schema/control/FhirSchemaVersion.java
  fhir-persistence-schema/src/main/java/com/ibm/fhir/schema/control/MigrateV0014LogicalResourceIsDeletedLastUpdated.java
  fhir-persistence-schema/src/main/java/com/ibm/fhir/schema/control/MigrateV0021AbstractTypeRemoval.java
  fhir-persistence-schema/src/main/java/com/ibm/fhir/schema/control/UnusedTableRemovalNeedsV0021Migration.java
  fhir-persistence-schema/src/test/java/com/ibm/fhir/schema/derby/DerbyFhirDatabaseTest.java
  fhir-persistence-schema/src/test/java/com/ibm/fhir/schema/derby/DerbySchemaVersionsTest.java
  operation/fhir-operation-member-match/src/main/java/com/ibm/fhir/operation/davinci/hrex/provider/strategy/DefaultMemberMatchStrategy.java
Labels: schema, schema-change

#2976 Update Website to use more secure libraries and switch to Yarn resolutions
  .github/workflows/site.yml
  docs/.babelrc
  docs/_config.yml
  docs/build-site.sh
  docs/create-fhir-validation-assembly.md
  docs/package-lock.json
  docs/package.json
  docs/readme.md
  docs/src/data/nav-items.yaml
  docs/yarn.lock
Labels: automation

#2982 Add registry init to beforeclass
  .github/workflows/build.yml
  .github/workflows/site.yml
  cql/fhir-cql-rest/src/test/java/com/ibm/fhir/cql/engine/rest/R4RestFHIRTest.java
  fhir-profile/src/test/java/com/ibm/fhir/profile/test/BPConstraintGeneratorTest.java
  fhir-profile/src/test/java/com/ibm/fhir/profile/test/ConstraintGeneratorTest.java
Labels: bug

#2990 AppScan Automation: The .irx is too large to analyze #2989
  build/security/asoc.sh
  docs/readme.md
Labels: automation, security

#3026 docs update only
  docs/package.json
  docs/yarn.lock
Labels: automation

#3027 Update README.md to remove projects that are not in main
  README.md
Labels: ci-skip

#3030 bulkdata: Add known limitation for fhir-persistence interceptor
  docs/src/pages/guides/FHIRServerUsersGuide.md
Labels: documentation

#3040 Remove undocumented feature for overriding the http method via header and related cleanup
  fhir-server/src/main/java/com/ibm/fhir/server/filter/rest/FHIRHttpServletRequestWrapper.java
  fhir-server/src/main/java/com/ibm/fhir/server/resources/Search.java
Labels: removal
