Repository LinuxForHealth/FHIR, pull requests merged in 2021-04, with the labels that each got.

#2191 Update MAINTAINERS.md
  MAINTAINERS.md
Labels: ci-skip

#2167 add environment section to bug template
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: ci-skip

#2204 fhir-server-test should have had all dependencies scoped to test
  fhir-server-test/pom.xml
Labels: automation, security

#2214 Issue #2162 - miscellaneous updates
  fhir-path/src/main/java/com/ibm/fhir/path/function/ExpandFunction.java
  fhir-path/src/main/java/com/ibm/fhir/path/function/LookupFunction.java
  fhir-path/src/main/java/com/ibm/fhir/path/function/MemberOfFunction.java
  fhir-path/src/main/java/com/ibm/fhir/path/function/TranslateFunction.java
  fhir-path/src/main/java/com/ibm/fhir/path/function/ValidateCSFunction.java
  fhir-path/src/main/java/com/ibm/fhir/path/function/ValidateVSFunction.java
  fhir-term-graph/src/main/java/com/ibm/fhir/term/graph/provider/GraphTermServiceProvider.java
  fhir-term-graph/src/main/java/com/ibm/fhir/term/graph/registry/SnomedRegistryResourceProvider.java
  fhir-term/src/main/java/com/ibm/fhir/term/service/ExpansionParameters.java
  fhir-term/src/main/java/com/ibm/fhir/term/service/FHIRTermService.java
  fhir-term/src/main/java/com/ibm/fhir/term/service/LookupOutcome.java
  fhir-term/src/main/java/com/ibm/fhir/term/service/LookupParameters.java
  fhir-term/src/main/java/com/ibm/fhir/term/service/TranslationOutcome.java
  fhir-term/src/main/java/com/ibm/fhir/term/service/TranslationParameters.java
  fhir-term/src/main/java/com/ibm/fhir/term/service/ValidationOutcome.java
  fhir-term/src/main/java/com/ibm/fhir/term/service/ValidationParameters.java
  fhir-term/src/main/java/com/ibm/fhir/term/service/provider/RegistryTermServiceProvider.java
  fhir-term/src/main/java/com/ibm/fhir/term/spi/FHIRTermServiceProvider.java
  fhir-term/src/main/java/com/ibm/fhir/term/util/CodeSystemSupport.java
  fhir-term/src/test/java/com/ibm/fhir/term/service/test/CodeSystemSupportTest.java
  fhir-term/src/test/java/com/ibm/fhir/term/service/test/FHIRTermServiceTest.java
  operation/fhir-operation-term/src/main/java/com/ibm/fhir/operation/term/AbstractTermOperation.java
  operation/fhir-operation-term/src/main/java/com/ibm/fhir/operation/term/CodeSystemValidateCodeOperation.java
  operation/fhir-operation-term/src/main/java/com/ibm/fhir/operation/term/ExpandOperation.java
  operation/fhir-operation-term/src/main/java/com/ibm/fhir/operation/term/LookupOperation.java
  operation/fhir-operation-term/src/main/java/com/ibm/fhir/operation/term/TranslateOperation.java
  operation/fhir-operation-term/src/main/java/com/ibm/fhir/operation/term/ValueSetValidateCodeOperation.java
Labels: terminology

#2217 ch.qos.logback:logback-core is vulnerable to CVE-2017-5929 #2216
  fhir-parent/pom.xml
Labels: security

#2223 Review the Dependencies for FHIR Term
  fhir-term-graph/pom.xml
Labels: automation

#2237 Update README.md
  README.md
Labels: ci-skip

#2253 formatting changes
  performance/fhir-meter/README.md
Labels: ci-skip

#2268 Issue #2198 - fixed typo, updated README
  README.md
  fhir-term/src/main/java/com/ibm/fhir/term/service/FHIRTermService.java
Labels: ci-skip

#2276 Issue #2198 - FHIRTerminologyGuide.md updates
  docs/src/pages/guides/FHIRTerminologyGuide.md
Labels: ci-skip
