Repository LinuxForHealth/FHIR, pull requests merged in 2021-05, with the labels that each got.

#2346 add _total documentation and move the subsetting info to 6.4
  docs/src/pages/guides/FHIRPerformanceGuide.md
Labels: documentation

#2351 Allocate Tenant without TenantKey Fails in the ibm-fhir-schematool on db2 #2349
  fhir-install/src/main/docker/ibm-fhir-schematool/Dockerfile
  fhir-install/src/main/docker/ibm-fhir-schematool/run.sh
  fhir-install/src/main/docker/ibm-fhir-schematool/tests/2349/2349.sh
  fhir-install/src/main/docker/ibm-fhir-schematool/tests/2349/docker-compose.yml
Labels: automation

#2359 Update to control the output of exceptions in ListTenants
  fhir-persistence-schema/src/main/java/com/ibm/fhir/schema/app/Main.java
Labels: ci-skip

#2368 Update per Sonatype Lift CVE Report
  fhir-parent/pom.xml
Labels: automation

#2372 GitHub Workflow - Javadocs version wasn't set
  .github/workflows/javadocs.yml
Labels: automation

#2376 Error on bulk data status call where import did not import anything #2322
  build/docker/copy-server-config.sh
  build/pre-integration-test-docker.sh
  fhir-bulkdata-webapp/src/main/java/com/ibm/fhir/bulkdata/jbatch/load/listener/ExitStatus.java
  fhir-bulkdata-webapp/src/main/java/com/ibm/fhir/bulkdata/load/partition/transformer/impl/S3Transformer.java
  fhir-server-test/src/test/java/com/ibm/fhir/server/test/bulkdata/ImportOperationTest.java
  fhir-server-test/src/test/resources/testdata/import-operation/test-import-neg.ndjson
Labels: bulk-data

#2395 Update Fetch to protect the count query
  fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/dao/impl/FetchResourcePayloadsDAO.java
Labels: bulk-data

#2403 Patient/$everything without a patientId results in a Null response. #2400
  fhir-server-test/src/test/java/com/ibm/fhir/server/test/everything/EverythingOperationTest.java
  operation/fhir-operation-everything/src/main/java/com/ibm/fhir/operation/everything/EverythingOperation.java
Labels: bug

#2408 issue 2405 fixed concurrent updates to correctly return 409 on version conflict
  fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/derby/DerbyResourceDAO.java
  fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/postgres/PostgresResourceNoProcDAO.java
  fhir-persistence-schema/src/main/resources/db2/add_any_resource.sql
  fhir-persistence-schema/src/main/resources/postgres/add_any_resource.sql
Labels: schema-change

#2416 Update to limit releases of fhir-examples
  build/release/bin/00_prep/0_install_packages.sh
  build/release/bin/10_build/2_version.sh
  build/release/bin/30_release/0_sonatype.sh
Labels: automation

#2394 Error on bulk data status call where import did not import anything.
  fhir-bulkdata-webapp/src/main/java/com/ibm/fhir/bulkdata/jbatch/listener/StepChunkListener.java
  fhir-bulkdata-webapp/src/main/java/com/ibm/fhir/bulkdata/jbatch/load/ImportJobListener.java
  fhir-bulkdata-webapp/src/main/java/com/ibm/fhir/bulkdata/jbatch/load/ImportPartitionMapper.java
  fhir-bulkdata-webapp/src/main/java/com/ibm/fhir/bulkdata/jbatch/load/exception/FHIRLoadException.java
  fhir-bulkdata-webapp/src/main/java/com/ibm/fhir/bulkdata/load/partition/transformer/impl/S3Transformer.java
  fhir-server-test/src/test/java/com/ibm/fhir/server/test/bulkdata/ImportOperationTest.java
  operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/OperationConstants.java
  operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/client/BulkDataClient.java
Labels: bulk-data

#2430 Update the Users Guide to correct issue with auth and update README.md with the Erase operation
  README.md
  docs/src/pages/guides/FHIRServerUsersGuide.md
Labels: ci-skip

#2412 Vanity URLs with AWS result in bucket NOT_FOUND on #2411
  fhir-bulkdata-webapp/src/main/java/com/ibm/fhir/bulkdata/provider/impl/S3Provider.java
Labels: bulk-data
