Repository LinuxForHealth/FHIR, pull requests merged in 2021-06, with the labels that each got.

#2446 Doc update #2364
  docs/src/pages/guides/FHIRPerformanceGuide.md
Labels: documentation

#2442 Set more specific batch bundle action in audit event when possible #1817
  docs/src/pages/guides/FHIRServerUsersGuide.md
  fhir-audit/src/main/java/com/ibm/fhir/audit/beans/Batch.java
  fhir-server/src/main/java/com/ibm/fhir/server/util/RestAuditLogger.java
Labels: audit

#2422 #2421 - Add terminology clear-cache operations
  README.md
  build/audit/kafka/pre-integration-test.sh
  build/docker/copy-test-operations.sh
  build/notifications/kafka/pre-integration-test.sh
  build/persistence/postgres/pre-integration-test.sh
  build/pre-integration-test.ps1
  build/pre-integration-test.sh
  fhir-parent/pom.xml
  fhir-server-test/src/test/java/com/ibm/fhir/server/test/terminology/CodeSystemClearCacheOperationTest.java
  fhir-server-test/src/test/java/com/ibm/fhir/server/test/terminology/TerminologyOperationTestBase.java
  fhir-server-test/src/test/java/com/ibm/fhir/server/test/terminology/ValueSetClearCacheOperationTest.java
  fhir-server-test/src/test/resources/testdata/CodeSystem-test-updated.json
  fhir-server-test/src/test/resources/testdata/ValueSet-extensional-updated.json
  fhir-server-test/src/test/resources/testdata/ValueSet-extensional.json
  fhir-server-test/src/test/resources/testdata/ValueSet-intensional-updated.json
  fhir-server-test/src/test/resources/testdata/ValueSet-intensional.json
  fhir-term/src/main/java/com/ibm/fhir/term/util/ValueSetSupport.java
  operation/fhir-operation-term-cache/README.md
  operation/fhir-operation-term-cache/pom.xml
  operation/fhir-operation-term-cache/src/main/java/com/ibm/fhir/operation/term/cache/CodeSystemClearCacheOperation.java
  operation/fhir-operation-term-cache/src/main/java/com/ibm/fhir/operation/term/cache/ValueSetClearCacheOperation.java
  operation/fhir-operation-term-cache/src/main/resources/META-INF/services/com.ibm.fhir.server.operation.spi.FHIROperation
  operation/fhir-operation-term-cache/src/main/resources/operation-codesystem-clear-cache.json
  operation/fhir-operation-term-cache/src/main/resources/operation-valueset-clear-cache.json
Labels: new-module

#2470 sudo build and release
  build/release/bin/00_prep/0_install_packages.sh
Labels: ci-skip

#2472 use proper ubuntu package for the xpath util
  build/release/bin/00_prep/0_install_packages.sh
Labels: ci-skip

#2475 attempt to free disk space before our docker build
  build/release/bin/30_release/1_dockerhub.sh
Labels: ci-skip

#2398 Use the "skippableUpdate" optimization during bulk import #2285
  docs/src/pages/guides/FHIRServerUsersGuide.md
  fhir-bulkdata-webapp/src/main/java/com/ibm/fhir/bulkdata/jbatch/load/ChunkWriter.java
  fhir-bulkdata-webapp/src/main/java/com/ibm/fhir/bulkdata/jbatch/load/data/ImportCheckPointData.java
  fhir-bulkdata-webapp/src/main/java/com/ibm/fhir/bulkdata/jbatch/load/listener/Reporter.java
  fhir-server-test/src/test/java/com/ibm/fhir/server/test/bulkdata/ImportOperationTest.java
  fhir-server-test/src/test/resources/testdata/import-operation/test-import.ndjson
  operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/config/ConfigurationAdapter.java
  operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/config/impl/AbstractSystemConfigurationImpl.java
Labels: bulk-data

#2380 Remove the exportPublic + ACL-based approach to exported object
  docs/src/pages/guides/FHIRServerUsersGuide.md
  fhir-bulkdata-webapp/src/main/java/com/ibm/fhir/bulkdata/common/BulkDataUtils.java
  fhir-bulkdata-webapp/src/main/java/com/ibm/fhir/bulkdata/jbatch/export/fast/ResourcePayloadReader.java
  fhir-bulkdata-webapp/src/main/java/com/ibm/fhir/bulkdata/jbatch/export/system/ChunkWriter.java
  fhir-bulkdata-webapp/src/main/java/com/ibm/fhir/bulkdata/jbatch/load/ImportPartitionCollector.java
  fhir-bulkdata-webapp/src/main/java/com/ibm/fhir/bulkdata/provider/Provider.java
  fhir-bulkdata-webapp/src/main/java/com/ibm/fhir/bulkdata/provider/impl/FileProvider.java
  fhir-bulkdata-webapp/src/main/java/com/ibm/fhir/bulkdata/provider/impl/HttpsProvider.java
  fhir-bulkdata-webapp/src/main/java/com/ibm/fhir/bulkdata/provider/impl/S3Provider.java
  fhir-config/src/main/java/com/ibm/fhir/config/FHIRConfiguration.java
  fhir-server/liberty-config/config/default/fhir-server-config-db2.json
  fhir-server/liberty-config/config/default/fhir-server-config.json
  operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/config/ConfigurationAdapter.java
  operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/config/impl/LegacyConfigurationImpl.java
  operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/config/impl/V2ConfigurationImpl.java
Labels: bulk-data, ci-skip

#2482 Support revocation of tenant keys #2211
  fhir-database-utils/src/main/java/com/ibm/fhir/database/utils/tenant/DeleteTenantKeyDAO.java
  fhir-persistence-schema/README.md
  fhir-persistence-schema/src/main/java/com/ibm/fhir/schema/app/Main.java
  fhir-persistence-schema/src/main/java/com/ibm/fhir/schema/app/util/CommonUtil.java
Labels: ci-skip, persistence

#2487 Cleanly handle tablespace removal error (fix for When multiple tenants exist, Drop Tenant Results in an incorrect FHIRDATA.PARAMETER_NAMES association and drop. #2354 )
  fhir-database-utils/src/main/java/com/ibm/fhir/database/utils/api/TableSpaceRemovalException.java
  fhir-persistence-schema/src/main/java/com/ibm/fhir/schema/app/Main.java
Labels: persistence

#2481 Audit record uses the exact value of: X-FHIR-FORWARDED-URL header as the URL called for the log entry #2473
  docs/src/pages/guides/FHIRServerUsersGuide.md
  fhir-server/src/main/java/com/ibm/fhir/server/util/RestAuditLogger.java
Labels: ci-skip

#2489 End-to-end automation test for reindexing #1751
  .github/workflows/reindex.yml
  build/common/gather-logs.sh
  build/reindex/.gitignore
  build/reindex/README.md
  build/reindex/bin/integration-test.sh
  build/reindex/bin/post-integration-test.sh
  build/reindex/bin/pre-integration-test.sh
  build/reindex/bin/setup-prerequisites.sh
  build/reindex/db2/.fhir.env
  build/reindex/db2/Dockerfile
  build/reindex/db2/create-database.sh
  build/reindex/db2/docker-compose.yml
  build/reindex/db2/pre-integration-test.sh
  build/reindex/db2/resources/startup.sh
  build/reindex/derby/.fhir.env
  build/reindex/derby/docker-compose.yml
  build/reindex/derby/pre-integration-test.sh
  build/reindex/postgres/.fhir.env
  build/reindex/postgres/Dockerfile
  build/reindex/postgres/docker-compose.yml
  build/reindex/postgres/pre-integration-test.sh
  build/reindex/postgres/resources/db.sql
  build/reindex/postgres/resources/docker-entrypoint.sh
  docs/src/pages/guides/FHIRSearchConfiguration.md
  fhir-examples/src/main/resources/json/ibm/basic/BasicDate.json
  fhir-server-test/src/test/java/com/ibm/fhir/server/test/operation/ReindexOperationLongRunTest.java
  fhir-server-test/src/test/java/com/ibm/fhir/server/test/operation/ReindexOperationPhase1Test.java
  fhir-server-test/src/test/java/com/ibm/fhir/server/test/operation/ReindexOperationPhase2Test.java
  fhir-server-test/src/test/java/com/ibm/fhir/server/test/operation/ReindexOperationPhase3Test.java
  fhir-server-test/src/test/java/com/ibm/fhir/server/test/operation/ReindexOperationTest.java
  fhir-server-test/src/test/resources/test.properties
  fhir-server-test/src/test/resources/testdata/reindex-operation/extension-search-parameters-test1.json
  fhir-server-test/src/test/resources/testdata/reindex-operation/extension-search-parameters-test2.json
  fhir-server/src/main/java/com/ibm/fhir/server/operation/FHIROperationRegistry.java
  operation/fhir-operation-reindex/src/main/java/com/ibm/fhir/operation/reindex/ReindexOperation.java
  operation/fhir-operation-reindex/src/main/resources/reindex.json
Labels: persistence

#2515 minor updates to CONTRIBUTING.md
  CONTRIBUTING.md
Labels: ci-skip

#2543 Remove isStorageProviderExportPublic and the legacy config impl
  docs/src/pages/guides/FHIRServerUsersGuide.md
  operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/config/ConfigurationAdapter.java
  operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/config/ConfigurationFactory.java
  operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/config/impl/LegacyConfigurationImpl.java
  operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/config/impl/V2ConfigurationImpl.java
Labels: removal

#2548 Per Testing with Azure Provider and Fix Skippable Logic
  fhir-bulkdata-webapp/src/main/java/com/ibm/fhir/bulkdata/jbatch/load/ChunkWriter.java
  fhir-bulkdata-webapp/src/main/java/com/ibm/fhir/bulkdata/provider/impl/AzureProvider.java
  fhir-bulkdata-webapp/src/test/java/com/ibm/fhir/bulkdata/provider/impl/AzureProviderMain.java
  operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/config/preflight/impl/AzurePreflight.java
Labels: bulk-data

#2559 Add Azure Preflight
  build/docker/db2/Dockerfile
  build/reindex/db2/Dockerfile
  docs/src/pages/guides/FHIRServerUsersGuide.md
  fhir-bulkdata-webapp/src/main/java/com/ibm/fhir/bulkdata/jbatch/export/checkpoint/ExportCheckpointAlgorithm.java
  fhir-bulkdata-webapp/src/main/java/com/ibm/fhir/bulkdata/jbatch/export/fast/ResourcePayloadReader.java
  fhir-bulkdata-webapp/src/main/java/com/ibm/fhir/bulkdata/jbatch/load/ChunkWriter.java
  fhir-bulkdata-webapp/src/main/java/com/ibm/fhir/bulkdata/provider/impl/AzureProvider.java
  fhir-server-test/src/test/java/com/ibm/fhir/server/test/bulkdata/ImportOperationTest.java
  fhir-server-test/src/test/resources/testdata/import-operation/test-import.ndjson
  operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/config/ConfigurationAdapter.java
  operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/config/impl/AbstractSystemConfigurationImpl.java
  operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/config/preflight/PreflightFactory.java
Labels: ci-skip
