Repository LinuxForHealth/FHIR, pull requests merged in 2021-08, with the labels that each got.

#2696 issue 2695 fix CONTRIBUTING.md build instructions
  CONTRIBUTING.md
Labels: ci-skip

#2693 FHIRNotificationService should emit event for patch update #2692
  fhir-notification/src/main/java/com/ibm/fhir/notification/FHIRNotificationService.java
Labels: fhir-notification

#2705 WHFFHIR-207 Write to a protected directory that is not needed, and fails when running SchemaTool/Db2 with a restricted user in openshift
  fhir-install/src/main/docker/ibm-fhir-schematool/run.sh
Labels: cloud portability

#2626 Update Datastore Migration
  .github/workflows/migration.yml
  build/common/gather-environment-details.sh
  build/common/wait_for_it.sh
  build/migration/.cache/.gitignore
  build/migration/.cache/README.md
  build/migration/.gitignore
  build/migration/README.md
  build/migration/bin/0_determine.sh
  build/migration/bin/1_check-cache.sh
  build/migration/bin/1_previous-setup.sh
  build/migration/bin/2_compose.sh
  build/migration/bin/2_previous-integration-test.sh
  build/migration/bin/3_previous-cache-startup.sh
  build/migration/bin/3_previous-teardown.sh
  build/migration/bin/4_current-migrate.sh
  build/migration/bin/5_current-pre-integration-test.sh
  build/migration/bin/6_current-reindex.sh
  build/migration/bin/7_current-integration-test.sh
  build/migration/bin/8_teardown.sh
  build/migration/db2/.fhir.env
  build/migration/db2/2_compose.sh
  build/migration/db2/3_previous-teardown.sh
  build/migration/db2/4_current-migrate.sh
  build/migration/db2/5_current-pre-integration-test.sh
  build/migration/db2/docker-compose.yml
  build/migration/db2/resources/Dockerfile
  build/migration/db2/resources/create-database.sh
  build/migration/postgres/.fhir.env
  build/migration/postgres/2_compose.sh
  build/migration/postgres/3_previous-teardown.sh
  build/migration/postgres/4_current-migrate.sh
  build/migration/postgres/5_current-pre-integration-test.sh
  build/migration/postgres/Dockerfile
  build/migration/postgres/docker-compose.yml
  build/migration/postgres/resources/db.sql
  build/migration/postgres/resources/docker-entrypoint.sh
Labels: automation

#2711 issue-2712 NPE when using a JsonPatch Remove on an already removed Field
  fhir-server-test/src/test/java/com/ibm/fhir/server/test/FHIRPatchTest.java
  fhir-server/src/main/java/com/ibm/fhir/server/util/FHIRRestHelper.java
Labels: bug
