Repository LinuxForHealth/FHIR, pull requests merged in 2022-02, with the labels that each got.

#3299 $member-match should throw FHIROperationException instead of rewrapping the exception #3298
  operation/fhir-operation-member-match/src/main/java/com/ibm/fhir/operation/davinci/hrex/provider/strategy/DefaultMemberMatchStrategy.java
Labels: bug

#3313 Contained Resources shouldn't be processed in Member Match #3312
  operation/fhir-operation-member-match/src/main/java/com/ibm/fhir/operation/davinci/hrex/provider/strategy/DefaultMemberMatchStrategy.java
  operation/fhir-operation-member-match/src/test/java/com/ibm/fhir/operation/davinci/hrex/test/MemberMatchIssuesTest.java
  operation/fhir-operation-member-match/src/test/resources/JSON/coverage.json
Labels: cms-interop

#3259 Update terminology dependencies
  fhir-examples/pom.xml
  fhir-parent/pom.xml
  term/fhir-term-graph-loader/pom.xml
  term/fhir-term-graph-loader/src/test/docker/docker-compose.yml
  term/fhir-term-graph/pom.xml
  term/fhir-term-graph/src/main/java/org/cliffc/high_scale_lib/NonBlockingHashMap.java
  term/fhir-term-graph/src/main/java/org/cliffc/high_scale_lib/NonBlockingHashMapLong.java
  term/fhir-term-graph/src/test/docker/docker-compose.yml
  term/fhir-term-graph/src/test/java/com/ibm/fhir/term/graph/test/FHIRTermGraphTest.java
  term/fhir-term-graph/src/test/java/com/ibm/fhir/term/graph/test/SnomedGraphTermServiceProviderTest.java
  term/fhir-term-graph/src/test/java/com/ibm/fhir/term/graph/test/SnomedRegistryResourceProviderTest.java
  term/fhir-term-graph/src/test/kubernetes/elasticsearch.yaml
  term/fhir-term-graph/src/test/kubernetes/k8ssandra.yaml
  term/fhir-term-graph/src/test/kubernetes/umlsTermGraphLoader.yml
Labels: automation

#3320 Exclude LGPL licensed dependencies
  fhir-parent/pom.xml
Labels: dependencies

#3297 Issue #2477 - Update to Java 11
  .github/workflows/build.yml
  docs/pom.xml
  docs/src/pages/announcement.mdx
  docs/src/pages/guides/FHIRModelGuide.mdx
  docs/src/pages/guides/FHIRServerUsersGuide.md
  fhir-benchmark/pom.xml
  fhir-bulkdata-webapp/pom.xml
  fhir-cache/src/main/java/com/ibm/fhir/cache/CacheManager.java
  fhir-database-utils/src/main/java/com/ibm/fhir/database/utils/streams/Streamer.java
  fhir-examples/pom.xml
  fhir-install/pom.xml
  fhir-install/src/main/assembly/distribution.xml
  fhir-install/src/main/resources/scripts/install.bat
  fhir-install/src/main/resources/scripts/install.sh
  fhir-parent/pom.xml
  fhir-server-test/src/test/java/com/ibm/fhir/server/test/SearchAllTest.java
  fhir-server-webapp/pom.xml
  fhir-tools/pom.xml
Labels: ci-skip

#3325 Update Implementation Guide Da Vinci Health Record Exchange (HRex) 0.2.0 - STU R1 - 2nd ballot #3253
  conformance/fhir-ig-davinci-hrex/CHANGELOG
  conformance/fhir-ig-davinci-hrex/README.md
  conformance/fhir-ig-davinci-hrex/src/main/resources/hl7/fhir/us/davinci-hrex/020/package/.index.json
  conformance/fhir-ig-davinci-hrex/src/main/resources/hl7/fhir/us/davinci-hrex/020/package/CodeSystem-hrex-temp.json
  conformance/fhir-ig-davinci-hrex/src/main/resources/hl7/fhir/us/davinci-hrex/020/package/ImplementationGuide-hl7.fhir.us.davinci-hrex.json
  conformance/fhir-ig-davinci-hrex/src/main/resources/hl7/fhir/us/davinci-hrex/020/package/OperationDefinition-member-match.json
  conformance/fhir-ig-davinci-hrex/src/main/resources/hl7/fhir/us/davinci-hrex/020/package/SearchParameter-hrex-coverage-identifier.json
  conformance/fhir-ig-davinci-hrex/src/main/resources/hl7/fhir/us/davinci-hrex/020/package/SearchParameter-hrex-coverage-patient.json
  conformance/fhir-ig-davinci-hrex/src/main/resources/hl7/fhir/us/davinci-hrex/020/package/SearchParameter-hrex-coverage-payor.json
  conformance/fhir-ig-davinci-hrex/src/main/resources/hl7/fhir/us/davinci-hrex/020/package/SearchParameter-hrex-coverage-subscriber.json
  conformance/fhir-ig-davinci-hrex/src/main/resources/hl7/fhir/us/davinci-hrex/020/package/SearchParameter-hrex-coverage-subscriberId.json
  conformance/fhir-ig-davinci-hrex/src/main/resources/hl7/fhir/us/davinci-hrex/020/package/SearchParameter-hrex-provenance-target.json
  conformance/fhir-ig-davinci-hrex/src/main/resources/hl7/fhir/us/davinci-hrex/020/package/StructureDefinition-extension-itemAuthorizedDate.json
  conformance/fhir-ig-davinci-hrex/src/main/resources/hl7/fhir/us/davinci-hrex/020/package/StructureDefinition-extension-itemAuthorizedProvider.json
  conformance/fhir-ig-davinci-hrex/src/main/resources/hl7/fhir/us/davinci-hrex/020/package/StructureDefinition-extension-itemPreAuthIssueDate.json
  conformance/fhir-ig-davinci-hrex/src/main/resources/hl7/fhir/us/davinci-hrex/020/package/StructureDefinition-extension-itemTraceNumber.json
  conformance/fhir-ig-davinci-hrex/src/main/resources/hl7/fhir/us/davinci-hrex/020/package/StructureDefinition-hrex-claimresponse.json
  conformance/fhir-ig-davinci-hrex/src/main/resources/hl7/fhir/us/davinci-hrex/020/package/StructureDefinition-hrex-consent.json
  conformance/fhir-ig-davinci-hrex/src/main/resources/hl7/fhir/us/davinci-hrex/020/package/StructureDefinition-hrex-coverage.json
  conformance/fhir-ig-davinci-hrex/src/main/resources/hl7/fhir/us/davinci-hrex/020/package/StructureDefinition-hrex-organization.json
  conformance/fhir-ig-davinci-hrex/src/main/resources/hl7/fhir/us/davinci-hrex/020/package/StructureDefinition-hrex-parameters-member-match-in.json
  conformance/fhir-ig-davinci-hrex/src/main/resources/hl7/fhir/us/davinci-hrex/020/package/StructureDefinition-hrex-parameters-member-match-out.json
  conformance/fhir-ig-davinci-hrex/src/main/resources/hl7/fhir/us/davinci-hrex/020/package/StructureDefinition-hrex-patient-demographics.json
  conformance/fhir-ig-davinci-hrex/src/main/resources/hl7/fhir/us/davinci-hrex/020/package/StructureDefinition-hrex-patient-member.json
  conformance/fhir-ig-davinci-hrex/src/main/resources/hl7/fhir/us/davinci-hrex/020/package/StructureDefinition-hrex-practitioner.json
  conformance/fhir-ig-davinci-hrex/src/main/resources/hl7/fhir/us/davinci-hrex/020/package/StructureDefinition-hrex-practitionerrole.json
  conformance/fhir-ig-davinci-hrex/src/main/resources/hl7/fhir/us/davinci-hrex/020/package/StructureDefinition-hrex-provenance.json
  conformance/fhir-ig-davinci-hrex/src/main/resources/hl7/fhir/us/davinci-hrex/020/package/StructureDefinition-hrex-task-data-request.json
  conformance/fhir-ig-davinci-hrex/src/main/resources/hl7/fhir/us/davinci-hrex/020/package/ValueSet-hrex-consent-policy.json
  conformance/fhir-ig-davinci-hrex/src/main/resources/hl7/fhir/us/davinci-hrex/020/package/ValueSet-hrex-task-status.json
  conformance/fhir-ig-davinci-hrex/src/main/resources/hl7/fhir/us/davinci-hrex/020/package/ig-r4.json
  conformance/fhir-ig-davinci-hrex/src/main/resources/hl7/fhir/us/davinci-hrex/020/package/package.json
  conformance/fhir-ig-davinci-hrex/src/test/resources/JSON/020/Bundle-subscription-notification-with-data.json
  conformance/fhir-ig-davinci-hrex/src/test/resources/JSON/020/Bundle-subscription-notification-with-document.json
  conformance/fhir-ig-davinci-hrex/src/test/resources/JSON/020/Bundle-task-poll-response.json
  conformance/fhir-ig-davinci-hrex/src/test/resources/JSON/020/Coverage-full.json
  conformance/fhir-ig-davinci-hrex/src/test/resources/JSON/020/Coverage-min.json
  conformance/fhir-ig-davinci-hrex/src/test/resources/JSON/020/Organization-full.json
  conformance/fhir-ig-davinci-hrex/src/test/resources/JSON/020/Organization-min.json
  conformance/fhir-ig-davinci-hrex/src/test/resources/JSON/020/Parameters-member-match-in-provider.json
  conformance/fhir-ig-davinci-hrex/src/test/resources/JSON/020/Parameters-member-match-in.json
  conformance/fhir-ig-davinci-hrex/src/test/resources/JSON/020/Practitioner-full.json
  conformance/fhir-ig-davinci-hrex/src/test/resources/JSON/020/Practitioner-min.json
  conformance/fhir-ig-davinci-hrex/src/test/resources/JSON/020/PractitionerRole-full.json
  conformance/fhir-ig-davinci-hrex/src/test/resources/JSON/020/PractitionerRole-min.json
  conformance/fhir-ig-davinci-hrex/src/test/resources/JSON/020/Provenance-full.json
  conformance/fhir-ig-davinci-hrex/src/test/resources/JSON/020/Provenance-min.json
  conformance/fhir-ig-davinci-hrex/src/test/resources/JSON/020/Task-document-complete.json
  conformance/fhir-ig-davinci-hrex/src/test/resources/JSON/020/Task-min.json
  conformance/fhir-ig-davinci-hrex/src/test/resources/JSON/020/Task-query-complete.json
  conformance/fhir-ig-davinci-hrex/src/test/resources/JSON/020/Task-query-initial.json
  conformance/fhir-ig-davinci-hrex/src/test/resources/JSON/020/Task-query-status.json
  fhir-server-test/src/test/java/com/ibm/fhir/server/test/profiles/DavinciHealthRecordExchangeTest.java
Labels: ci-skip

#3337 list of flags needs updating #3332
  fhir-persistence-schema/docs/SchemaToolUsageGuide.md
Labels: documentation, ci-skip

#3335 issues #3216 and #2512 - support for alternative reference schemes and bundle ref resolution from FHIRPath ResolveFunction
  fhir-bucket/src/main/java/com/ibm/fhir/bucket/scanner/BundleBreakerResourceProcessor.java
  fhir-model/src/main/java/com/ibm/fhir/model/util/FHIRUtil.java
  fhir-model/src/main/java/com/ibm/fhir/model/util/ValidationSupport.java
  fhir-model/src/test/java/com/ibm/fhir/model/util/test/ReferenceMappingVisitorTest.java
  fhir-model/src/test/java/com/ibm/fhir/model/util/test/ValidationSupportReferenceTest.java
  fhir-model/src/test/java/com/ibm/fhir/model/util/test/ValidationSupportValueSetTest.java
  fhir-path/src/main/java/com/ibm/fhir/path/function/ResolveFunction.java
  fhir-path/src/test/java/com/ibm/fhir/path/test/ResolveFunctionTest.java
  fhir-path/src/test/java/com/ibm/fhir/path/test/ResolveInternalFragmentReferenceTest.java
  fhir-server/src/test/java/com/ibm/fhir/server/util/FHIRRestHelperTest.java
Labels: ci-skip, removal

#3359 Bulk Data Import with missing 'id' on Audit #3016
  fhir-bulkdata-webapp/src/main/java/com/ibm/fhir/bulkdata/audit/BulkAuditLogger.java
  fhir-bulkdata-webapp/src/main/java/com/ibm/fhir/bulkdata/jbatch/load/ChunkWriter.java
Labels: ci-skip

#3360 Bulk Data import job with pod restarts unable to delete #3033
  docs/src/pages/guides/FHIRServerUsersGuide.md
  fhir-server-webapp/src/main/liberty/config/configDropins/defaults/bulkdata.xml
  fhir-server-webapp/src/main/liberty/config/configDropins/disabled/db2-cloud/bulkdata.xml
  fhir-server-webapp/src/main/liberty/config/configDropins/disabled/postgres/bulkdata.xml
Labels: ci-skip

#3363 Patch ModelResolver to return Resource.id as FHIR.string
  cql/fhir-cql/src/main/java/com/ibm/fhir/cql/engine/model/FHIRModelResolver.java
  cql/fhir-cql/src/test/java/com/ibm/fhir/cql/engine/model/FHIRModelResolverTest.java
  cql/operation/fhir-operation-cpg/src/test/java/com/ibm/fhir/operation/cpg/CqlOperationTest.java
  fhir-server-test/src/test/java/com/ibm/fhir/server/test/cpg/ServerCqlOperationTest.java
Labels: cql

#3379 introduce links to the helm chart
  README.md
Labels: ci-skip

#3381 Issue 3000: Update per QA
  fhir-bulkdata-webapp/src/main/java/com/ibm/fhir/bulkdata/jbatch/load/ChunkReader.java
  fhir-bulkdata-webapp/src/main/java/com/ibm/fhir/bulkdata/jbatch/load/ImportPartitionAnalyzer.java
  fhir-bulkdata-webapp/src/main/java/com/ibm/fhir/bulkdata/jbatch/load/listener/Reporter.java
Labels: bulk-data

#3357 BulkData 2.0.0: Update the OperationDefinitions and CapabilityStatement #3082
  fhir-server-test/src/test/java/com/ibm/fhir/server/test/bulkdata/ExportOperationTest.java
  fhir-server-webapp/pom.xml
  operation/fhir-operation-bulkdata/README.md
  operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/ExportOperation.java
  operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/GroupExportOperation.java
  operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/PatientExportOperation.java
  operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/util/BulkDataExportUtil.java
  operation/fhir-operation-bulkdata/src/main/resources/export-group.json
  operation/fhir-operation-bulkdata/src/main/resources/export-patient.json
  operation/fhir-operation-bulkdata/src/main/resources/export.json
  operation/fhir-operation-bulkdata/src/main/resources/hl7/fhir/uv/bulkdata/package/.index.json
  operation/fhir-operation-bulkdata/src/main/resources/hl7/fhir/uv/bulkdata/package/CapabilityStatement-bulk-data.json
  operation/fhir-operation-bulkdata/src/main/resources/hl7/fhir/uv/bulkdata/package/CodeSystem-include-associated-data.json
  operation/fhir-operation-bulkdata/src/main/resources/hl7/fhir/uv/bulkdata/package/ImplementationGuide-hl7.fhir.uv.bulkdata.json
  operation/fhir-operation-bulkdata/src/main/resources/hl7/fhir/uv/bulkdata/package/OperationDefinition-export.json
  operation/fhir-operation-bulkdata/src/main/resources/hl7/fhir/uv/bulkdata/package/OperationDefinition-group-export.json
  operation/fhir-operation-bulkdata/src/main/resources/hl7/fhir/uv/bulkdata/package/OperationDefinition-patient-export.json
  operation/fhir-operation-bulkdata/src/main/resources/hl7/fhir/uv/bulkdata/package/ValueSet-include-associated-data.json
  operation/fhir-operation-bulkdata/src/main/resources/hl7/fhir/uv/bulkdata/package/package.json
  operation/fhir-operation-bulkdata/src/test/java/com/ibm/fhir/operation/bulkdata/util/BulkDataExportUtilTest.java
Labels: bulk-data

#3380 Issue 3106 - Update per QA
  fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/dao/impl/ResourceReferenceDAO.java
  fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/postgres/PostgresResourceReferenceDAO.java
Labels: persistence

#3382 bulkdata preflight checks should verify output provider config #2709
  fhir-bulkdata-webapp/src/main/java/com/ibm/fhir/bulkdata/provider/impl/S3Provider.java
  fhir-server/pom.xml
  operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/ImportOperation.java
  operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/client/S3ClientGenerator.java
  operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/config/impl/AbstractSystemConfigurationImpl.java
  operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/config/preflight/Preflight.java
  operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/config/preflight/impl/S3Preflight.java
Labels: bulk-data

#3386 Bulk Data NPE with _TYPE on Get
  operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/util/BulkDataExportUtil.java
  operation/fhir-operation-bulkdata/src/test/java/com/ibm/fhir/operation/bulkdata/util/BulkDataExportUtilTest.java
Labels: bulk-data

#3388 Issue with QA on #3083
  operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/config/preflight/impl/FilePreflight.java
  operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/util/BulkDataExportUtil.java
  operation/fhir-operation-bulkdata/src/test/java/com/ibm/fhir/operation/bulkdata/config/preflight/impl/FilePreflightTest.java
  operation/fhir-operation-bulkdata/src/test/java/com/ibm/fhir/operation/bulkdata/util/BulkDataExportUtilTest.java
Labels: bulk-data
