Repository LinuxForHealth/FHIR, pull requests merged in 2022-01, with the labels that each got.

#3189 AccessTokens should not be set with Presigned URLs #3188
  docs/src/pages/guides/FHIRServerUsersGuide.md
  operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/config/ConfigurationAdapter.java
  operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/config/impl/V2ConfigurationImpl.java
Labels: ci-skip

#3197 set GITHUB_REF to the ref/tag we're rebuilding
  .github/workflows/rebuild.yml
  build/release/bin/global/2_verify_build_settings.sh
Labels: ci-skip

#3187 #3061 - Fix NPE when Measure refers to non-existent library
  cql/fhir-cql/src/main/java/com/ibm/fhir/cql/helpers/LibraryHelper.java
  cql/fhir-quality-measure/src/main/java/com/ibm/fhir/ecqm/r4/MeasureHelper.java
  cql/operation/fhir-operation-cpg/src/main/java/com/ibm/fhir/operation/cpg/AbstractCqlOperation.java
  cql/operation/fhir-operation-cpg/src/main/java/com/ibm/fhir/operation/cpg/CqlOperation.java
  cql/operation/fhir-operation-cpg/src/main/java/com/ibm/fhir/operation/cpg/ParameterConverter.java
  cql/operation/fhir-operation-cqf/src/main/java/com/ibm/fhir/operation/cqf/AbstractDataRequirementsOperation.java
  cql/operation/fhir-operation-cqf/src/main/java/com/ibm/fhir/operation/cqf/AbstractMeasureOperation.java
  cql/operation/fhir-operation-cqf/src/main/java/com/ibm/fhir/operation/cqf/CareGapsOperation.java
  cql/operation/fhir-operation-cqf/src/main/java/com/ibm/fhir/operation/cqf/EvaluateMeasureOperation.java
  cql/operation/fhir-operation-cqf/src/main/java/com/ibm/fhir/operation/cqf/MeasureDataRequirementsOperation.java
  cql/operation/fhir-operation-cqf/src/main/java/com/ibm/fhir/operation/cqf/MeasureSubmitDataOperation.java
  cql/operation/fhir-operation-cqf/src/main/java/com/ibm/fhir/operation/cqf/OperationHelper.java
  cql/operation/fhir-operation-cqf/src/test/java/com/ibm/fhir/operation/cqf/BaseDataRequirementsOperationTest.java
  cql/operation/fhir-operation-cqf/src/test/java/com/ibm/fhir/operation/cqf/EvaluateMeasureOperationTest.java
  cql/operation/fhir-operation-cqf/src/test/java/com/ibm/fhir/operation/cqf/MeasureDataRequirementsOperationTest.java
  fhir-server-test/src/test/java/com/ibm/fhir/server/test/cqf/BaseMeasureOperationTest.java
  fhir-server-test/src/test/java/com/ibm/fhir/server/test/cqf/ServerEvaluateMeasureOperationTest.java
  fhir-server-test/src/test/java/com/ibm/fhir/server/test/cqf/ServerMeasureCollectDataOperationTest.java
  fhir-server-test/src/test/resources/testdata/Measure-MissingLibrary.json
  fhir-server-test/src/test/resources/testdata/Measure-NoLibrary.json
Labels: cql

#3205 Erroneous reporting of Pending Outcome in Audit #3204
  fhir-audit/src/main/java/com/ibm/fhir/audit/mapper/impl/AuditEventMapper.java
  fhir-audit/src/main/java/com/ibm/fhir/audit/mapper/impl/CADFMapper.java
Labels: ci-skip

#3208 patch the release script to avoid bad test
  .github/workflows/rebuild.yml
Labels: ci-skip

#3210 #3195 - Bubble up exception message from CQL engine
  cql/operation/fhir-operation-cpg/src/main/java/com/ibm/fhir/operation/cpg/AbstractCqlOperation.java
  cql/operation/fhir-operation-cpg/src/main/java/com/ibm/fhir/operation/cpg/CqlOperation.java
  cql/operation/fhir-operation-cpg/src/main/java/com/ibm/fhir/operation/cpg/LibraryEvaluateOperation.java
  fhir-server-test/src/test/java/com/ibm/fhir/server/test/cpg/ServerCqlOperationTest.java
  fhir-server-test/src/test/java/com/ibm/fhir/server/test/cqf/ServerEvaluateMeasureOperationTest.java
Labels: cql

#3220 Update README.md
  README.md
Labels: ci-skip

#3222 Update Db2 JCC to Latest
  fhir-parent/pom.xml
Labels: automation

#3223 Update cxf-rt-transports-http-hc to agree with cxf deps
  fhir-parent/pom.xml
Labels: automation

#3218 tell maven its ok if some modules have no tests
  .github/workflows/rebuild.yml
  build/release/bin/20_test/1_code_coverage.sh
Labels: ci-skip

#3225 Update to clean up the dependency trees
  fhir-parent/pom.xml
  fhir-server-test/pom.xml
  fhir-server/pom.xml
  term/fhir-term-graph/pom.xml
Labels: automation, security

#3236 Update per dependabot alert on node-fetch
  docs/package.json
  docs/yarn.lock
Labels: ci-skip

#3215 Issue 2694 update schema design docs
  CONTRIBUTING.md
  docs/src/pages/Conformance.md
  docs/src/pages/guides/DB2OnCloudSetup.md
  docs/src/pages/guides/FHIRBulkOperations.md
  docs/src/pages/guides/FHIRServerUsersGuide.md
  fhir-bucket/README.md
  fhir-install/src/main/docker/ibm-fhir-bucket-tool/README.md
  fhir-install/src/main/docker/ibm-fhir-schematool/README.md
  fhir-install/src/main/docker/ibm-fhir-term-graph-loader/README.md
  fhir-persistence-schema/README.md
  fhir-persistence-schema/docs/DB2MultiTenancy.md
  fhir-persistence-schema/docs/SchemaDesign.md
  fhir-persistence-schema/docs/SchemaMigration.md
  fhir-persistence-schema/docs/SchemaToolUsageGuide.md
  fhir-persistence-schema/docs/mt-table.png
  fhir-persistence-schema/docs/physical_schema_V0024.png
  fhir-persistence-schema/docs/resource_schema.png
Labels: ci-skip
