Repository LinuxForHealth/FHIR, pull requests merged in 2022-08, with the labels that each got.

#3830 issue #3681 - fail the schema-update if there are existing Evidence o…
  fhir-persistence-schema/src/main/java/com/ibm/fhir/schema/app/Main.java
  fhir-persistence-schema/src/main/java/com/ibm/fhir/schema/control/FhirSchemaVersion.java
  fhir-persistence-schema/src/main/java/com/ibm/fhir/schema/control/TableHasData.java
  fhir-persistence-schema/src/test/java/com/ibm/fhir/schema/derby/DerbyFhirDatabaseTest.java
  fhir-persistence-schema/src/test/java/com/ibm/fhir/schema/derby/DerbySchemaVersionsTest.java
Labels: enhancement, P2

#3835 issue #3834 removed references to Db2 in documentation
  README.md
  build/migration/README.md
  build/reindex/README.md
  docs/src/pages/guides/DB2OnCloudSetup.md
  docs/src/pages/guides/FHIRPerformanceGuide.md
  docs/src/pages/guides/FHIRServerUsersGuide.md
  fhir-bucket/README.md
  fhir-install/src/main/docker/ibm-fhir-schematool/DESIGN.md
  fhir-install/src/main/docker/ibm-fhir-schematool/DEVELOPMENT.md
  fhir-install/src/main/docker/ibm-fhir-schematool/README.md
  fhir-install/src/main/docker/ibm-fhir-schematool/examples/db2/persistence-debug-custom.json
  fhir-install/src/main/docker/ibm-fhir-schematool/examples/db2/persistence-debug-example.json
  fhir-install/src/main/docker/ibm-fhir-schematool/examples/db2/persistence-offboard-example.json
  fhir-install/src/main/docker/ibm-fhir-schematool/examples/db2/persistence-onboard-example.json
  fhir-persistence-blob-app/README.md
  fhir-persistence-jdbc/README-JDBC-Performance-Tests.md
  fhir-remote-index/README.md
  operation/fhir-operation-erase/README.md
Labels: ci-skip

#3841 issue #2964 - Support resource-instance level validate operation and …
  operation/fhir-operation-validate/pom.xml
  operation/fhir-operation-validate/src/main/java/com/ibm/fhir/operation/validate/ValidateOperation.java
  operation/fhir-operation-validate/src/main/java/com/ibm/fhir/operation/validate/type/ModeType.java
  operation/fhir-operation-validate/src/test/java/com/ibm/fhir/operation/validate/ValidateOperationTest.java
Labels: enhancement

#3871 issue #3870 added 5.0.1 to README.md
  conformance/fhir-ig-us-core/README.md
Labels: ci-skip

#3891 remove the check for DockerHub username and token
  build/release/bin/global/2_verify_build_settings.sh
Labels: ci-skip

#3897 update ossrh endpoint in one more spot
  fhir-examples/pom.xml
Labels: ci-skip

#3899 another release fix
  build/release/bin/30_release/0_sonatype.sh
Labels: ci-skip

#3901 dependency version bumps
  fhir-examples/pom.xml
  fhir-parent/pom.xml
Labels: dependencies

#3918 issue-2964 - adding validations for interaction, mode paramter and in…
  fhir-server-test/src/test/java/org/linuxforhealth/fhir/server/test/FHIROperationTest.java
  operation/fhir-operation-validate/src/main/java/org/linuxforhealth/fhir/operation/validate/ValidateOperation.java
  operation/fhir-operation-validate/src/main/java/org/linuxforhealth/fhir/operation/validate/type/ModeType.java
  operation/fhir-operation-validate/src/test/java/org/linuxforhealth/fhir/operation/validate/ValidateOperationTest.java
Labels: bug
