Repository LinuxForHealth/FHIR, pull requests merged in 2022-03, with the labels that each got.

#3412 Update MAINTAINERS.md
  MAINTAINERS.md
Labels: ci-skip

#3431 Update Rest Audit Logger
  fhir-server/src/main/java/com/ibm/fhir/server/util/RestAuditLogger.java
Labels: audit

#3440 issue #2886 - remove useStoredCompartmentParam property
  docs/src/pages/guides/FHIRPerformanceGuide.md
  docs/src/pages/guides/FHIRSearchConfiguration.md
  docs/src/pages/guides/FHIRServerUsersGuide.md
  fhir-config/src/main/java/com/ibm/fhir/config/FHIRConfiguration.java
  fhir-search/src/main/java/com/ibm/fhir/search/util/SearchHelper.java
  fhir-search/src/test/java/com/ibm/fhir/search/test/CompartmentParseQueryParmsTest.java
  fhir-search/src/test/resources/config/tenant2/fhir-server-config.json
  fhir-server-webapp/src/main/liberty/config/config/default/fhir-server-config.json
Labels: ci-skip

#3442 issue #3091 - Add resources to their own compartment
  docs/src/pages/guides/FHIRSearchConfiguration.md
  fhir-persistence-jdbc/src/main/java/com/ibm/fhir/persistence/jdbc/impl/FHIRPersistenceJDBCImpl.java
  fhir-persistence/src/test/java/com/ibm/fhir/persistence/test/common/AbstractCompartmentTest.java
  fhir-search/src/main/java/com/ibm/fhir/search/compartment/CompartmentHelper.java
  fhir-search/src/main/java/com/ibm/fhir/search/util/SearchHelper.java
  fhir-server-test/src/test/java/com/ibm/fhir/server/test/operation/EverythingOperationTenant1Test.java
  fhir-server-test/src/test/java/com/ibm/fhir/server/test/operation/EverythingOperationTest.java
Labels: ci-skip

#3483 bump liberty from 21.0.0.12 to 22.0.0.3
  fhir-install/Dockerfile
  fhir-install/src/main/resources/scripts/install.bat
  fhir-install/src/main/resources/scripts/install.sh
  fhir-parent/pom.xml
Labels: dependencies

#3482 issue #3319 - normalize handling of _type parameters
  docs/src/pages/Conformance.md
  fhir-install/Dockerfile
  fhir-install/src/main/resources/scripts/install.bat
  fhir-install/src/main/resources/scripts/install.sh
  fhir-parent/pom.xml
  fhir-server-spi/pom.xml
  fhir-server-spi/src/main/java/com/ibm/fhir/server/spi/operation/FHIROperationUtil.java
  fhir-server-spi/src/test/java/com/ibm/fhir/server/spi/operation/test/FHIROperationUtilTest.java
  fhir-server-test/src/test/java/com/ibm/fhir/server/test/bulkdata/ExportOperationTest.java
  fhir-server/src/main/java/com/ibm/fhir/server/util/FHIRRestHelper.java
  operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/ExportOperation.java
  operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/client/BulkDataClient.java
  operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/model/url/DownloadUrl.java
  operation/fhir-operation-bulkdata/src/main/java/com/ibm/fhir/operation/bulkdata/util/BulkDataExportUtil.java
  operation/fhir-operation-bulkdata/src/test/java/com/ibm/fhir/operation/bulkdata/util/BulkDataExportUtilTest.java
  operation/fhir-operation-everything/src/main/java/com/ibm/fhir/operation/everything/EverythingOperation.java
Labels: ci-skip

#3499 issue #3414 updated docs with new blob offload size limit
  fhir-persistence-blob-app/README.md
Labels: ci-skip

#3542 issue #3508 updated numConnectionsPerThreadLocal guidance in performance guide
  docs/src/pages/guides/FHIRPerformanceGuide.md
Labels: ci-skip
